// The CFA Financial District — the whole CFA Level I curriculum as one low-poly
// island city, walked in 27 stops.
//
// Model: blender_models/CFAFinancialDistrict.blend, built by
// blender_models/cfa_scenegen/cfa_*.py; export prep in
// scripts/cfa_level_1_export.py.
//
// THE ONE RULE THE SCENE ENCODES: every building's height IS its exam weight
// (midpoint of the published range x 1.6 m). Ethics is a 28 m marble
// courthouse; Derivatives is a 10.4 m pit. The skyline is the weighting.
//
// Layout: a round plaza with the Charterholder's Compass at its centre, a ring
// boulevard, and ten buildings on the outside of the ring, one per topic area,
// in curriculum order CLOCKWISE from the north-north-east — Ethics,
// Quantitative Methods, Economics, Financial Statement Analysis, Corporate
// Issuers, Equity, Fixed Income, Derivatives, Alternative Investments,
// Portfolio Management. Each district's forecourt carries one to three
// plinths; each plinth is one locus, with a low-poly memory peg on it and a
// tilted name plate in front.
//
// Tour: 1 the south gate (how the exam works), 2 the compass (height =
// weight), then 3–27 clockwise round the ring. The ring closes, so it reads in
// either direction — recall is not locked to one direction of travel.
//
// Camera: peg stops park the rig 8.6 m inside the plinth on the ray from the
// plaza centre, looking outward, so the peg fills the frame and the name plate
// sits along the bottom edge (a NEGATIVE anchorDistance = distance from the
// locus on the centroid side). Locus 1 and 2 stand off outward instead.
// Locus_01..27 are baked into the .blend (collection 09_Loci); build_glb.py's
// SCENES entry is empty. Every number below is three.js space, metres, and is
// generated from cfa_layout.py — keep the two in step.

export default {
  // Come in high over the south gate with the whole island in frame.
  startView: {
    position: [0, 128, 272],
    lookAt: [0, 6, 0],
  },
  walkthrough: {
    travelSeconds: 5,
    dwellSeconds: 18,
    eyeHeight: 0.8,
    anchorDistance: -8.6,
    loop: true,
  },
  background: 0xb9d3e6,
  fog: { near: 170, far: 560 },
  lighting: {
    hemisphere: 0.95,
    ambient: 0.22,
    ambientColor: 0xfff2e2,
    sun: 1.25,
    // The island is ~232 m across, centred on the origin.
    shadowExtent: 104,
    environment: true,
    environmentIntensity: 0.45,
    environmentColor: 0xe8eef4,
  },
  labels: { worldSize: 0.5, offsetY: 2.4 },
  loci: [
    {
      id: 1,
      title: "The South Gate — what Level I actually is",
      description: "The CFA Program is three exams. LEVEL I is this island: the whole vocabulary of investing, tested as 180 multiple-choice questions in two 135-minute sessions on one day, 90 questions each, three answer choices per question, no penalty for guessing. It is offered several times a year in a computer-based window, and it is the one level that asks you to KNOW things rather than judge them: the command words are describe, calculate, explain, identify. Level II then applies the same material to item sets (vignettes) and valuation; Level III turns it into portfolio management and essays. Four years of qualified work experience and CFA Institute membership turn the three passes into a charter.\n\nHOW TO WALK THIS CITY: a ring boulevard with ten buildings on the outside, one per topic area, in curriculum order clockwise from the north-north-east: Ethics, Quantitative Methods, Economics, Financial Statement Analysis, Corporate Issuers, Equity, Fixed Income, Derivatives, Alternative Investments, Portfolio Management. In front of each stands one to three plinths — the memory pegs. Walk it in either direction; the ring closes, so nothing is locked to one order of recall.",
      position: [0.0, 6.4, 94.0],
      anchorFrom: [0, 0, 0],
      anchorDistance: 26.0,
      eyeHeight: 4.5,
      labelColor: "#dcae3c",
      labelPosition: [0.0, 12.0, 94.0],
    },
    {
      id: 2,
      title: "The Charterholder's Compass — height is weight",
      description: "The one rule that makes this city a memory palace: EVERY BUILDING'S HEIGHT IS ITS EXAM WEIGHT. Each is the midpoint of the published range times 1.6 metres, so the skyline you see from the gate IS the weighting, and the ten bronze spokes of this compass point at each district with a length that matches.\n\nETHICS 15-20% (28 m, the tallest thing on the island, and the tiebreaker: borderline scores are decided on the ethics sections). FINANCIAL STATEMENT ANALYSIS 11-14%, EQUITY 11-14%, FIXED INCOME 11-14% (three equal 20 m slabs — together more than a third of the exam). PORTFOLIO MANAGEMENT 8-12% (16 m). ALTERNATIVE INVESTMENTS 7-10% (13.6 m). QUANTITATIVE METHODS 6-9%, ECONOMICS 6-9%, CORPORATE ISSUERS 6-9% (three 12 m mid-rises). DERIVATIVES 5-8% (10.4 m, the runt in the pit).\n\nNinety-three learning modules sit inside those ten. The three tiers above you — gold, silver, gold — are the three levels; the light on top is the charter.",
      position: [0.0, 5.2, -0.0],
      anchorFrom: [0, 0, -40],
      anchorDistance: 24.0,
      eyeHeight: 6.0,
      labelColor: "#dcae3c",
      labelPosition: [0.0, 10.4, -0.0],
    },
    {
      id: 3,
      title: "Ethics · The Code — six lines you can be asked to rank",
      description: "The CODE OF ETHICS is six components, and the exam loves the order of priority they imply. Members and candidates must: (1) act with INTEGRITY, COMPETENCE, DILIGENCE and RESPECT, in an ethical manner, with the public, clients, prospective clients, employers, employees, colleagues and other market participants; (2) place the INTEGRITY OF THE PROFESSION and the INTERESTS OF CLIENTS above their own personal interests; (3) use REASONABLE CARE and exercise INDEPENDENT PROFESSIONAL JUDGEMENT; (4) PRACTISE AND ENCOURAGE OTHERS to practise professionally and ethically, reflecting credit on the profession; (5) PROMOTE THE INTEGRITY AND VIABILITY of the global capital markets for the ultimate benefit of society; (6) MAINTAIN AND IMPROVE their competence and that of other professionals.\n\nPEG: the Code lies open on its lectern under a ring of SIX gold pips. Beside it the scale tips toward the small figure — the client. That tilt is the whole of component 2, and it is the answer to most ethics vignettes: client interests before your own, always, and the profession before your employer.\n\nThe ETHICAL DECISION-MAKING FRAMEWORK is four steps: IDENTIFY (facts, duties, conflicts) → CONSIDER (situational influences, alternatives, get guidance) → ACT → REFLECT.",
      position: [24.96, 4.02, -44.46],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#d8b450",
      labelPosition: [24.96, 6.92, -44.46],
    },
    {
      id: 4,
      title: "Ethics · The Seven Standards — I to VII",
      description: "Seven marble columns, each capped in its own colour. Learn the roman numerals; the vignettes quote them.\n\nI PROFESSIONALISM — (A) Knowledge of the Law, (B) Independence and Objectivity, (C) Misrepresentation, (D) Misconduct.\nII INTEGRITY OF CAPITAL MARKETS — (A) Material Nonpublic Information, (B) Market Manipulation.\nIII DUTIES TO CLIENTS — (A) Loyalty, Prudence and Care, (B) Fair Dealing, (C) Suitability, (D) Performance Presentation, (E) Preservation of Confidentiality. The tallest column: the client's standard, and the one most often tested.\nIV DUTIES TO EMPLOYERS — (A) Loyalty, (B) Additional Compensation Arrangements, (C) Responsibilities of Supervisors.\nV INVESTMENT ANALYSIS, RECOMMENDATIONS AND ACTIONS — (A) Diligence and Reasonable Basis, (B) Communication with Clients, (C) Record Retention (seven years is the recommended minimum).\nVI CONFLICTS OF INTEREST — (A) Disclosure of Conflicts, (B) Priority of Transactions, (C) Referral Fees.\nVII RESPONSIBILITIES AS A MEMBER OR CANDIDATE — (A) Conduct in CFA Institute Programs, (B) Reference to CFA Institute, the CFA Designation and the CFA Program.\n\nRULES OF THUMB that decide most questions: where local law and the Code differ, follow the STRICTER. Gifts from clients may be accepted with disclosure; gifts from anyone else that could compromise independence, refuse. \"CFA\" is an adjective, never a noun, and there is no such thing as a \"CFA Level II candidate\" — you are \"a candidate in the CFA Program\".",
      position: [15.45, 4.02, -47.55],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#d8b450",
      labelPosition: [15.45, 6.92, -47.55],
    },
    {
      id: 5,
      title: "Ethics · GIPS — one lighthouse, every firm the same light",
      description: "The GLOBAL INVESTMENT PERFORMANCE STANDARDS are voluntary, ethical standards for how a firm presents its own track record, built on two ideas: FAIR REPRESENTATION and FULL DISCLOSURE. The point is comparability — without them, a firm can show only the accounts that did well.\n\nWhat to remember: compliance is FIRM-WIDE, never claimed for a single composite or product; the firm must define itself as a distinct business entity. A COMPOSITE is all actual, fee-paying, discretionary portfolios managed to a similar strategy — every such portfolio must be in at least one composite, so the winners cannot be cherry-picked. A minimum of FIVE years of compliant history (or since inception if shorter), building to TEN. Returns are time-weighted and must include cash. VERIFICATION by an independent third party is optional, applies to the whole firm, and can never be claimed for one composite alone. GIPS does not certify anyone — the firm claims compliance itself.\n\nPEG: the lighthouse on a rock of stacked composites, shining the same beam on every ship, whatever each firm would rather show you.",
      position: [5.94, 4.02, -50.64],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#d8b450",
      labelPosition: [5.94, 6.92, -50.64],
    },
    {
      id: 6,
      title: "Quant · Time value of money — the staircase and the clock",
      description: "Five stacks of coins growing left to right, under a clock: money has a price, and the price is TIME.\n\nFV = PV(1 + r)^n, and with m compounding periods a year FV = PV(1 + r/m)^(mn); continuously, FV = PV·e^(rn). Reverse the arrow and you are discounting: PV = FV / (1 + r)^n. An ORDINARY ANNUITY pays at the END of each period, an ANNUITY DUE at the beginning — so annuity due = ordinary × (1 + r). A PERPETUITY is PV = PMT / r, which is also the Gordon growth formula waiting to happen.\n\nTHE REQUIRED RETURN IS A STACK: nominal risk-free = real risk-free + expected inflation, and then add a DEFAULT risk premium, a LIQUIDITY premium and a MATURITY premium. That stack reappears in fixed income as the credit spread and in equity as the required return on equity.\n\nRETURN MEASURES, and the distinction examiners keep coming back to: HOLDING PERIOD RETURN is the simple total return; the MONEY-WEIGHTED return is just the IRR of the cash flows, so it is dominated by WHEN the client added or withdrew money; the TIME-WEIGHTED return chains sub-period returns and strips those flows out, which is why it is the standard for judging a MANAGER. Geometric mean ≤ arithmetic mean, always; use the geometric to describe past compounding and the arithmetic to estimate one future period.",
      position: [44.57, 4.02, -23.73],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#7fd0e8",
      labelPosition: [44.57, 6.92, -23.73],
    },
    {
      id: 7,
      title: "Quant · Distributions, tests and regression",
      description: "The bell curve with both tails painted red, and beside it a scatter with a rod driven through it.\n\nDESCRIBE IT: mean, median, mode; variance and standard deviation (divide by n−1 for a SAMPLE); coefficient of variation = s / mean, the unit-free risk-per-unit-of-return. SKEW — right/positive skew has the long tail up and mean > median. KURTOSIS — leptokurtic means fat tails; excess kurtosis = kurtosis − 3, and financial returns are famously fat-tailed and negatively skewed.\n\nNORMAL: symmetric, fully described by μ and σ²; about 68% within 1σ, 95% within 2σ (1.96 exactly), 99% within 2.58σ. The CENTRAL LIMIT THEOREM says the sample MEAN is approximately normal for n ≥ 30 whatever the population, with standard error σ/√n — which is why bigger samples give tighter confidence intervals.\n\nTEST IT: state H0 (what you try to reject) and Ha. A TYPE I error rejects a true null — its probability is α, the significance level, the red tails on the peg. A TYPE II error fails to reject a false null — probability β; power = 1 − β. Reject when the test statistic falls in the rejection region, or equivalently when the p-value < α. t-test for a mean, chi-square for a single variance, F-test for two variances.\n\nREGRESS IT: Y = b0 + b1X + ε, fitted by least squares. R² is the fraction of the variation in Y explained by X; the standard error of estimate is the typical size of a residual. Correlation is not causation, it only catches LINEAR relationships, and one outlier can invent or destroy it.",
      position: [36.34, 4.02, -35.05],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#7fd0e8",
      labelPosition: [36.34, 6.92, -35.05],
    },
    {
      id: 8,
      title: "Economics · Four market structures, and the scissors",
      description: "Four stalls, shrinking in number and growing in size, under the crossing blades of supply and demand.\n\nPERFECT COMPETITION — very many sellers, identical product, free entry, no pricing power at all: the firm is a price TAKER and produces where P = MR = MC. Long-run economic profit is zero.\nMONOPOLISTIC COMPETITION — many sellers, DIFFERENTIATED product, so a downward-sloping demand curve, some pricing power, heavy advertising, and again zero economic profit in the long run as imitators arrive.\nOLIGOPOLY — a few interdependent sellers; what you do depends on what you think the others will do. This is where the models live: kinked demand, Cournot, Stackelberg, Nash equilibrium, and cartels that keep collapsing because cheating pays.\nMONOPOLY — one seller, high barriers, a price MAKER that sets quantity where MR = MC and then reads the price off the demand curve. Price discrimination raises profit further. Concentration is measured by the N-firm concentration ratio (ignores mergers among leaders) and better by the HERFINDAHL-HIRSCHMAN INDEX, the sum of squared market shares.\n\nELASTICITY: own-price (elastic if |e| > 1 — then a price cut RAISES revenue), cross-price (positive = substitutes, negative = complements), income (negative = inferior good).\n\nTHE SHUTDOWN RULES: in the short run, keep producing while P ≥ AVC (you are still covering variable cost and something toward fixed); shut down if P < AVC. In the long run, exit if P < ATC. And economic profit subtracts OPPORTUNITY cost, not just the accountant's cost.",
      position: [50.0, 4.02, 7.0],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e2c76a",
      labelPosition: [50.0, 6.92, 7.0],
    },
    {
      id: 9,
      title: "Economics · The cycle, the two levers, and the FX booth",
      description: "An economy riding a wave, a lever on one side, a dial on the other, a currency booth at the back.\n\nGDP is the market value of all final goods and services produced in a period. Expenditure approach: C + I + G + (X − M). Nominal uses current prices, real uses base-year prices; the GDP deflator is the ratio. THE BUSINESS CYCLE runs trough → expansion → peak → contraction; inventories and unemployment are the classic late signals — inventory-to-sales RISES at the top because sales fall before production does.\n\nPRICES: CPI overstates inflation (substitution, quality, new goods); core strips food and energy. Demand-pull comes from an economy above potential, cost-push from wages or input prices. UNEMPLOYMENT: frictional (between jobs, unavoidable), structural (skills mismatch, needs retraining), cyclical (the one policy targets); discouraged workers and the underemployed are not counted as unemployed, which flatters the rate.\n\nTHE TWO LEVERS. FISCAL is the GOVERNMENT'S — taxes and spending; powerful but slow to legislate, and subject to crowding out. MONETARY is the CENTRAL BANK'S — the policy rate, open-market operations, reserve requirements; quick to act, but works with long and variable lags and is impotent against a liquidity trap. Expansionary monetary + contractionary fiscal tends to push rates down; the reverse pushes them up.\n\nTHE FX BOOTH: a quote is price currency / base currency, and the base is the one you are buying. Real exchange rates adjust for inflation; PURCHASING POWER PARITY says the currency with higher inflation depreciates; COVERED INTEREST RATE PARITY says the currency with the HIGHER interest rate trades at a forward DISCOUNT — otherwise there is free money.",
      position: [50.0, 4.02, -7.0],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e2c76a",
      labelPosition: [50.0, 6.92, -7.0],
    },
    {
      id: 10,
      title: "FSA · The three statements",
      description: "A three-tier stack: a beam that must balance, a funnel that narrows, three pipes.\n\nTHE BALANCE SHEET is a PHOTOGRAPH — one instant. ASSETS = LIABILITIES + EQUITY, and it balances by construction; that is the beam. Current vs non-current; equity is contributed capital + retained earnings + accumulated other comprehensive income − treasury stock.\n\nTHE INCOME STATEMENT is a FILM — a period. Revenue at the wide end, then cost of goods sold → GROSS PROFIT, then operating expenses → OPERATING INCOME (EBIT), then interest and tax → NET INCOME at the spout. Basic EPS = (net income − preferred dividends) / weighted average shares; diluted EPS assumes convertibles and options convert. Accrual accounting means revenue is recognised when control of the good or service transfers, not when the cash lands — which is exactly why the third statement exists.\n\nTHE STATEMENT OF CASH FLOWS is three pipes. CFO — the business itself. CFI — buying and selling long-lived assets and investments. CFF — borrowing, repaying, issuing shares, paying dividends. The INDIRECT method starts at net income and adds back non-cash charges and working-capital changes (an increase in a receivable is a USE of cash); the direct method lists the receipts and payments. Classification differs: under US GAAP interest paid and received and dividends received are CFO and dividends paid are CFF; under IFRS interest and dividends paid may be CFO or CFF, and interest and dividends received may be CFO or CFI.\n\nTHE TEST QUESTION BEHIND ALL OF IT: net income grows while CFO stagnates — look at receivables and inventory first.",
      position: [34.57, 4.02, 37.48],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f6f1e2",
      labelPosition: [34.57, 6.92, 37.48],
    },
    {
      id: 11,
      title: "FSA · Inventory, long-lived assets and tax — where the judgement lives",
      description: "A chute taking crates off the top or the bottom, a machine walking down a ramp, two rulebooks with a box between them.\n\nINVENTORY. Permitted: FIFO, weighted average cost, specific identification, and — under US GAAP ONLY — LIFO. In RISING prices, LIFO puts the newest, dearest units into cost of goods sold: higher COGS, LOWER gross profit, lower net income, lower TAXES (its real attraction), and a balance-sheet inventory stuck at old, understated prices. FIFO does the opposite: inventory close to current cost, income higher. To compare, add the LIFO RESERVE back to inventory and adjust COGS. LIFO liquidation — selling old cheap layers — inflates margins unsustainably. Write-downs: IFRS uses lower of cost or NET REALISABLE VALUE and ALLOWS reversals; US GAAP (for LIFO and retail) uses lower of cost or market and NEVER reverses.\n\nLONG-LIVED ASSETS. CAPITALISE and you get an asset, higher first-year income, smoother later income, and the spend sits in CFI; EXPENSE and you get lower income now, higher later, and the spend sits in CFO — same cash either way. Depreciate straight-line, declining balance (accelerated: lower early income) or units of production. IFRS permits a REVALUATION model; US GAAP does not. Impair when the carrying amount is not recoverable; IFRS allows reversal of impairments, US GAAP does not.\n\nINCOME TAXES. Taxable income follows the tax code, reported income follows the accounting standard, and the gap between them is the amber box: TEMPORARY differences create deferred tax liabilities (e.g. accelerated depreciation for tax) or deferred tax assets (e.g. carry-forwards), and reverse; PERMANENT differences (tax-exempt interest, non-deductible fines) never reverse and instead move the EFFECTIVE tax rate away from the statutory one.",
      position: [40.45, 4.02, 29.39],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f6f1e2",
      labelPosition: [40.45, 6.92, 29.39],
    },
    {
      id: 12,
      title: "FSA · Ratios, DuPont and reporting quality",
      description: "A wall of five gauges, a gold triangle, and a strip running green to red.\n\nTHE FIVE FAMILIES. ACTIVITY — inventory turnover, days of inventory on hand, receivables turnover, days sales outstanding, total asset turnover. LIQUIDITY — current, quick ((cash + marketable securities + receivables)/current liabilities) and cash ratios. SOLVENCY — debt-to-equity, debt-to-capital, financial leverage, interest coverage (EBIT/interest). PROFITABILITY — gross, operating and net margin, ROA, ROE. VALUATION — P/E, P/B, P/S, P/CF. A ratio means nothing alone: compare across time and against peers using the same accounting choices.\n\nDUPONT, the gold triangle. Three-part: ROE = NET PROFIT MARGIN × ASSET TURNOVER × FINANCIAL LEVERAGE — profitability, efficiency, debt. Five-part splits the margin further: TAX BURDEN (NI/EBT) × INTEREST BURDEN (EBT/EBIT) × EBIT MARGIN × asset turnover × leverage. Its whole purpose is to answer WHY ROE moved — a rising ROE driven only by leverage is not the same news as one driven by margin.\n\nTHE QUALITY SPECTRUM, green to red: compliant AND decision-useful → compliant but BIASED choices → compliant but earnings MANAGEMENT (real decisions taken to hit a number) → NON-COMPLIANT → FICTITIOUS transactions. Note that high EARNINGS quality and high REPORTING quality are different things: you can report sustainable bad news honestly. Warning signs: revenue growing faster than receivables can explain, capitalising what peers expense, one-offs that recur every year, a widening gap between net income and CFO. Screens: the Beneish M-score for manipulation, the Altman Z-score for bankruptcy risk.",
      position: [46.33, 4.02, 21.3],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f6f1e2",
      labelPosition: [46.33, 6.92, 21.3],
    },
    {
      id: 13,
      title: "Corporate Issuers · Governance and the people around the table",
      description: "Six figures around one round table under the gavel, and a ring of stakeholders outside it.\n\nSTRUCTURES: sole proprietorship and partnerships (unlimited liability for general partners, the business and the owner taxed as one) versus the CORPORATION — limited liability, unlimited life, and the fact that matters here: SEPARATION OF OWNERSHIP AND CONTROL. Public companies face disclosure and a liquid market for their shares; private ones do not.\n\nSTAKEHOLDERS all want something different: SHAREHOLDERS have a residual claim and like risk-taking (their downside is capped at zero); CREDITORS have a fixed claim and hate it; MANAGERS want tenure, pay and empire; the BOARD is meant to referee; employees, customers, suppliers and governments sit outside. Every governance problem on the exam is one of the PRINCIPAL–AGENT conflicts between two of those rings — manager vs shareholder (empire-building, perks, entrenchment), shareholder vs creditor (taking on risky projects with the creditors' money), controlling vs minority shareholder.\n\nMECHANISMS: an INDEPENDENT board with a separate chair and its committees — AUDIT, REMUNERATION, NOMINATION, RISK; shareholder voting, STATUTORY (one share one vote per seat) versus CUMULATIVE (pool your votes onto one candidate — which is what lets minorities elect a director); proxy voting; say on pay; the market for corporate control. Dual-class shares, staggered boards and poison pills cut the other way. ESG analysis sits here too.",
      position: [8.79, 4.02, 49.72],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#c9d2da",
      labelPosition: [8.79, 6.92, 49.72],
    },
    {
      id: 14,
      title: "Corporate Issuers · The three capital decisions",
      description: "A loop that never stops, a gate only good projects pass, and a column part blue part gold.\n\nWORKING CAPITAL — the loop. CASH CONVERSION CYCLE = days of inventory on hand + days sales outstanding − days payables outstanding. Shorter is better: it is how long your own cash is tied up. Manage the pieces (collect faster, stretch payables without damaging suppliers) and keep committed credit lines rather than uncommitted ones, because uncommitted lines vanish exactly when you need them.\n\nCAPITAL ALLOCATION — the gate. Use INCREMENTAL after-tax cash flows: ignore SUNK costs, include OPPORTUNITY costs and externalities (cannibalisation counts, and so does a positive spillover). Accept a project when NPV > 0, or equivalently when IRR > the required return — but when projects are mutually exclusive or differ in size or timing, the two can disagree and NPV ALWAYS WINS, because NPV is the value added in currency and assumes reinvestment at the cost of capital rather than at the IRR. Real options (abandon, expand, defer) add value NPV alone misses.\n\nCAPITAL STRUCTURE — the column. MODIGLIANI–MILLER with no taxes: capital structure is IRRELEVANT, value comes from the assets (Proposition I), and the cost of equity rises exactly enough with leverage to leave WACC unchanged (Proposition II). Add corporate taxes and interest is deductible, so a tax shield makes debt cheap and, in the pure model, more is always better. Reality is the STATIC TRADE-OFF: the tax shield versus the costs of financial distress, giving an optimal ratio where WACC is lowest. PECKING ORDER says managers prefer internal funds, then debt, then equity — and an equity issue is read as a signal that the shares are dear.",
      position: [22.11, 4.02, 45.39],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#c9d2da",
      labelPosition: [22.11, 6.92, 45.39],
    },
    {
      id: 15,
      title: "Equity · Markets, orders and indexes",
      description: "A limit order book — green bids stacked under red asks — a ticker ribbon overhead, and a basket of weighted balls.\n\nTHE BOOK. A MARKET order takes the best price available now and guarantees execution, not price. A LIMIT order names a price and guarantees price, not execution. A STOP order sleeps until the market trades through a trigger and then becomes a market order — the classic stop-loss. Bids below, asks above, the spread between.\n\nPOSITIONS AND LEVERAGE. Long profits when the price rises; SHORT sells borrowed stock, profits when it falls, and has theoretically unlimited loss — the short also owes the dividends. On MARGIN: leverage ratio = 1 / initial margin requirement; the margin call price on a long buy = P0 × (1 − initial margin) / (1 − maintenance margin).\n\nMARKET STRUCTURE: quote-driven (you trade with a dealer), order-driven (you trade with another investor through the book), brokered (the broker finds the counterparty — for illiquid, unique assets). PRIMARY markets raise new capital (IPO, seasoned offering, private placement); SECONDARY markets only transfer ownership, and their real function is providing the liquidity that makes the primary market possible.\n\nINDEXES, the basket. PRICE-WEIGHTED (the Dow) — a simple average adjusted by a divisor; a high-priced share dominates regardless of size, and splits distort it. EQUAL-WEIGHTED — a small-cap tilt and it must be rebalanced constantly. MARKET-CAP WEIGHTED (float-adjusted; most major indexes) — self-rebalancing, but carries a momentum tilt: the more a stock rises, the more of it you hold. Rebalancing resets weights; RECONSTITUTION changes the membership.",
      position: [-24.96, 4.02, 44.46],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f0c05a",
      labelPosition: [-24.96, 6.92, 44.46],
    },
    {
      id: 16,
      title: "Equity · Market efficiency — three walls",
      description: "Three walls of rising thickness, and a random walk wandering past all of them.\n\nIn an EFFICIENT market, prices already reflect information, so the expected reward for finding it is zero after costs. Fama's three forms are three walls:\n\nWEAK FORM — prices already reflect all PAST MARKET DATA (prices, volume, short interest). If it holds, TECHNICAL ANALYSIS cannot earn abnormal returns. Largely supported in developed markets.\nSEMI-STRONG FORM — prices reflect all PUBLIC information, market data plus financial statements, news, filings. If it holds, FUNDAMENTAL ANALYSIS on public data cannot earn abnormal returns either; prices adjust at the moment of announcement, not after. Mostly supported in developed markets.\nSTRONG FORM — prices reflect public AND PRIVATE information. Then even insiders cannot profit — and the evidence says they can, which is why insider dealing is illegal and why this wall does not hold.\n\nThe paradox worth carrying: it takes active analysts trying to beat the market to MAKE it efficient, so efficiency cannot be complete or nobody would look.\n\nANOMALIES that refuse to die: calendar effects (the January effect in small caps), MOMENTUM, the VALUE and SIZE effects, post-earnings-announcement drift, closed-end fund discounts, overreaction. Most shrink once transaction costs, data-mining and risk adjustment are taken seriously. BEHAVIOURAL FINANCE explains the rest by assuming investors are not rational — see locus 27.",
      position: [-15.45, 4.02, 47.55],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f0c05a",
      labelPosition: [-15.45, 6.92, 47.55],
    },
    {
      id: 17,
      title: "Equity · Valuation — three ways to name a price",
      description: "A fountain that keeps pouring, a P/E stamp, and a cube with five arrows pressing on it.\n\nPRESENT VALUE MODELS — the fountain. A share is worth the present value of what it pays you. DIVIDEND DISCOUNT: V0 = Σ Dt/(1+r)^t. With constant growth this collapses to the GORDON GROWTH MODEL, V0 = D1 / (r − g), which needs g < r and is violently sensitive to both — shrink the gap and the value explodes. The sustainable growth rate g = RETENTION RATIO × ROE, which is why a company that pays everything out cannot grow from its own earnings. For firms that pay no dividend, use FREE CASH FLOW TO EQUITY instead.\n\nMULTIPLES — the stamp. P/E (trailing uses the last four quarters, leading uses forecasts; meaningless on negative earnings), P/B (useful for banks and for loss-makers), P/S (hardest to manipulate), P/CF, and enterprise-value multiples like EV/EBITDA, which are capital-structure neutral. A multiple is a COMPARISON, not a valuation: it only means something against peers, against history, or justified from fundamentals (leading P/E = payout ratio / (r − g)).\n\nASSET-BASED — the floor: adjusted net asset value; realistic for resource and financial firms, poor for businesses whose value is intangible.\n\nTHE CUBE AND THE FIVE ARROWS — Porter: rivalry among existing competitors, threat of NEW ENTRANTS, threat of SUBSTITUTES, bargaining power of SUPPLIERS, bargaining power of BUYERS. They are what decide whether the g you just typed into the Gordon model can survive contact with an industry.",
      position: [-5.94, 4.02, 50.64],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f0c05a",
      labelPosition: [-5.94, 6.92, 50.64],
    },
    {
      id: 18,
      title: "Fixed Income · A bond taken apart",
      description: "A certificate with its coupon tabs still attached, the par-value brick returned at the end, and the two issuers behind it: a government dome and a corporate tower.\n\nTHE FOUR FEATURES: ISSUER, MATURITY (tenor), PAR (face) value, and COUPON — plus the currency it is denominated in. Coupons can be FIXED, FLOATING (a reference rate plus a quoted margin, reset each period, so the price barely moves with rates) or ZERO (issued at a discount, all return from the pull to par). Bullet bonds repay principal in one lump; AMORTISING bonds repay it along the way; sinking funds retire it in stages.\n\nTHE CONTRACT: the INDENTURE sets out everything; COVENANTS are the promises — AFFIRMATIVE (keep insurance, file statements, maintain ratios) and NEGATIVE (do not issue senior debt, do not sell assets, do not exceed a leverage limit). Negative covenants cost the issuer flexibility and buy the bondholder protection, which shows up as a lower yield.\n\nEMBEDDED OPTIONS, and who owns them: CALLABLE favours the ISSUER (refinance when rates fall), so the investor demands a HIGHER yield and a lower price. PUTABLE favours the INVESTOR (hand it back), so a LOWER yield. CONVERTIBLE gives the investor equity upside — lower yield again.\n\nTHE ISSUERS: sovereigns, non-sovereign and quasi-government, supranationals (the World Bank, the EIB), and corporates — commercial paper at the short end, medium-term notes and bonds beyond, plus repo for funding. Primary issues come underwritten, on a best-efforts basis, by auction (how most sovereigns sell) or by private placement; almost all secondary trading is over the counter.",
      position: [-46.33, 4.02, 21.3],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e6d2a8",
      labelPosition: [-46.33, 6.92, 21.3],
    },
    {
      id: 19,
      title: "Fixed Income · Price, yield and the shape of the curve",
      description: "A seesaw with price on one end and yield on the other, and behind it a board with three curves.\n\nTHE SEESAW IS THE WHOLE SUBJECT: price and yield move in OPPOSITE directions, because the price is just the present value of fixed cash flows. If the coupon rate is BELOW the market yield, the bond trades at a DISCOUNT; above it, at a PREMIUM; equal, at PAR. Whatever it starts at, the price PULLS TO PAR as maturity approaches.\n\nPRICING PROPERLY: discount each cash flow at its own SPOT rate, not one yield-to-maturity — and the spot curve implies FORWARD rates, which are the rates you can lock in today for a future period. Arbitrage keeps the two consistent.\n\nYIELD MEASURES. CURRENT YIELD is only coupon / price. YIELD TO MATURITY is the IRR of the bond, and its three silent assumptions are the exam's favourite trap: you HOLD TO MATURITY, the issuer NEVER DEFAULTS, and every coupon is REINVESTED AT THE YTM. For a callable bond compute yield to each call date and quote the lowest, the YIELD TO WORST. SPREADS: the G-spread over a government bond, the I-spread over a swap rate, the Z-SPREAD added to every spot rate to make the price work, and the OAS — the Z-spread with the value of the embedded option stripped out, which is the only fair way to compare a callable with a bullet.\n\nTHREE SHAPES: NORMAL, upward-sloping (green); FLAT (yellow); INVERTED, long rates below short (red), historically the market's most-watched recession signal. Explanations: pure EXPECTATIONS (forwards are unbiased forecasts), LIQUIDITY PREFERENCE (a positive term premium for lending longer), SEGMENTED MARKETS (each maturity has its own supply and demand) and PREFERRED HABITAT (investors will move, at a price).",
      position: [-40.45, 4.02, 29.39],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e6d2a8",
      labelPosition: [-40.45, 6.92, 29.39],
    },
    {
      id: 20,
      title: "Fixed Income · Duration, convexity and credit",
      description: "A plank balanced on a fulcrum with the coupons laid along it, a credit ladder behind, and a pool of houses sliced into tranches.\n\nDURATION IS A BALANCE POINT. MACAULAY duration is literally the weighted average time to receipt of a bond's cash flows — the point where the plank balances. MODIFIED duration = Macaulay / (1 + y) and is the one you use: the approximate PERCENTAGE price change for a 1% change in yield. Money duration gives it in currency; PVBP is the price change for one basis point. EFFECTIVE duration is the version for bonds whose cash flows can change — callables, putables, MBS — and key rate durations show exposure to individual points on the curve.\n\nWHAT MAKES DURATION LARGER: longer maturity, LOWER coupon, LOWER yield. (A zero-coupon bond's Macaulay duration IS its maturity.)\n\nCONVEXITY IS THE CORRECTION. The price–yield line is a curve, not a straight line, so duration alone overstates the fall when yields rise and understates the gain when they drop. %ΔP ≈ −ModDur × Δy + ½ × Convexity × (Δy)². Positive convexity is a free good, which is why callable bonds — which go NEGATIVELY convex near the call price — are penalised.\n\nCREDIT, the ladder. EXPECTED LOSS = PROBABILITY OF DEFAULT × LOSS GIVEN DEFAULT, and the credit spread is the market's price for it. Investment grade stops at BBB− / Baa3; below that is high yield, and the step down matters because many mandates cannot hold it. Analysts use the four Cs — CAPACITY, COLLATERAL, COVENANTS, CHARACTER — and notch individual issues up or down from the issuer rating by seniority. Spreads widen in downturns exactly when equity falls, so credit is not the diversifier it looks like.\n\nSECURITISATION, the pool: loans are sold to a bankruptcy-remote SPE, which issues TRANCHES paid in a waterfall — senior first, then mezzanine, then the equity piece that absorbs the first losses. Mortgage-backed securities add PREPAYMENT risk: rates fall and borrowers refinance (CONTRACTION risk); rates rise and they sit tight (EXTENSION risk).",
      position: [-34.57, 4.02, 37.48],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e6d2a8",
      labelPosition: [-34.57, 6.92, 37.48],
    },
    {
      id: 21,
      title: "Derivatives · Forward commitments",
      description: "Two people shaking hands over a private deal, the same deal standardised inside a cleared box with a margin meter, and two payment streams crossing. The whole district stands on water, because a derivative's value DERIVES from something underneath it.\n\nA FORWARD COMMITMENT obliges BOTH sides. A FORWARD is the handshake: over the counter, customised in size, date and terms, settled at expiry, and carrying COUNTERPARTY RISK — the other side may not be there. A FUTURE is the same economic deal made public: exchange-traded, STANDARDISED, guaranteed by a CLEARINGHOUSE, and MARKED TO MARKET daily against an initial and a maintenance margin, so the credit risk is settled away one day at a time (that daily settlement is also why futures and forward prices differ when rates and prices are correlated). A SWAP is a series of forwards bundled together — a plain vanilla interest-rate swap exchanges a fixed stream for a floating one, and at inception it is worth zero to both sides.\n\nTHE PRICE COMES FROM ARBITRAGE, not from a forecast. Replicate the forward by borrowing and buying the asset today: F0 = S0(1 + r)^T, then adjust for CARRY — subtract the benefits of holding the asset (dividends, coupons, convenience yield) and add the costs (storage, insurance). If the quoted price differs, you can buy cheap, sell dear, and lock a riskless profit, which is why it cannot.\n\nWHAT THEY ARE FOR: hedging, cheap and fast exposure, price discovery, and reaching markets you cannot trade directly. WHAT THEY COST: leverage cuts both ways, OTC contracts carry counterparty and liquidity risk, and complexity hides all of it.",
      position: [-50.0, 4.02, -7.0],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#9fe0d8",
      labelPosition: [-50.0, 6.92, -7.0],
    },
    {
      id: 22,
      title: "Derivatives · Options — a right, not an obligation",
      description: "The road forks and only the branch that pays gets taken; beside it one binomial node splitting the world in two, and the put-call parity scale.\n\nA CONTINGENT CLAIM pays only if something happens. The BUYER of an option pays a PREMIUM for the RIGHT, not the obligation, to transact — so the buyer's loss is capped at the premium and the SELLER (writer), who took the premium, carries the open-ended risk. A CALL is the right to buy at the exercise price; a PUT is the right to sell. EUROPEAN options exercise only at expiry, AMERICAN any time before, which is why an American option is never worth less.\n\nVALUE = EXERCISE (INTRINSIC) VALUE + TIME VALUE. A call is in the money when S > X, a put when S < X; intrinsic value is never negative because you simply do not exercise. Time value decays to zero at expiry.\n\nSIX DRIVERS. Call value rises with the UNDERLYING price, falls with the EXERCISE price; put the reverse. Both rise with VOLATILITY — the single most important driver, because more dispersion means more upside and no more downside. More TIME to expiry helps (almost always). A higher RISK-FREE RATE helps calls, hurts puts. Carry BENEFITS (dividends) hurt calls, help puts; carry COSTS the reverse.\n\nPUT–CALL PARITY, the scale: S + p = c + PV(X). A share plus a protective put equals a call plus cash — the two pans must balance, or there is arbitrage. Rearranged it builds a SYNTHETIC anything.\n\nTHE ONE-PERIOD BINOMIAL: the underlying either rises by u or falls by d; value the option as the expected payoff under the RISK-NEUTRAL probability π = (1 + r − d) / (u − d), discounted at the risk-free rate. No one's real forecast of the probability appears anywhere — that is the point.",
      position: [-50.0, 4.02, 7.0],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#9fe0d8",
      labelPosition: [-50.0, 6.92, 7.0],
    },
    {
      id: 23,
      title: "Alternatives · The seven kinds in the yard",
      description: "Seven things on one table, because the definition of an \"alternative\" is really just: not a public stock, bond or cash.\n\nPRIVATE EQUITY (the briefcase) — buyouts (mature companies, leverage, operational change) and VENTURE capital (early stage, most lose, a few return the fund). Exit by trade sale, secondary sale or IPO.\nPRIVATE DEBT (the note) — direct lending, mezzanine, distressed, venture debt: the same borrowers, from the other side of the balance sheet.\nREAL ESTATE (the block) — four quadrants: private equity (direct ownership), private debt (mortgages), public equity (REITs), public debt (MBS). An income stream plus an inflation hedge.\nINFRASTRUCTURE (the bridge) — long-lived public assets; GREENFIELD is built from nothing, BROWNFIELD is already operating. Long, stable, often regulated or inflation-linked cash flows.\nNATURAL RESOURCES (the derrick and the pine) — commodities, timberland, farmland. Commodities pay no cash flow at all: the return is spot price change plus roll yield plus collateral yield.\nHEDGE FUNDS (the shield) — a fee structure and a legal wrapper more than a strategy. Four broad groups: equity (long/short, market neutral), event-driven (merger arb, distressed), relative value (fixed-income arb, convertible arb) and opportunistic/macro (global macro, managed futures).\nDIGITAL ASSETS (the glowing cube) — cryptocurrencies, tokens, stablecoins and the distributed ledgers underneath them.\n\nWHY ANY OF IT: returns from illiquidity and skill rather than beta, and low reported correlation with public markets — though \"reported\" is doing real work in that sentence. See the next plinth.",
      position: [-36.34, 4.02, -35.05],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e8b168",
      labelPosition: [-36.34, 6.92, -35.05],
    },
    {
      id: 24,
      title: "Alternatives · What it costs and what it really returns",
      description: "The 2-and-20 gate — a thin yearly slice and a fat fifth of the profit — a curve that dips before it climbs, a line you must get back above, and a lock on the door.\n\nTHE STRUCTURE. Most private funds are LIMITED PARTNERSHIPS: the GENERAL PARTNER runs it and is liable; the LIMITED PARTNERS commit capital and are drawn down over an investment period. Funds of funds add diversification and a second layer of fees.\n\nTHE FEES. A MANAGEMENT FEE of roughly 1-2% — note whether it is charged on COMMITTED or on INVESTED capital, because it changes the answer. Then an INCENTIVE FEE, classically 20% of profits, called CARRIED INTEREST in private equity. Three brakes on it: a HURDLE RATE (no carry until the LPs earn a preferred return, often 8%), a HIGH-WATER MARK (no carry on gains that merely recover a previous loss — the cyan line), and a CLAWBACK (give it back if later losses show the GP was paid too early). Waterfalls come EUROPEAN (whole-of-fund: LPs get all capital and the preferred return first — LP friendly) or AMERICAN (deal-by-deal — GP friendly). Fees on gross return can eat a third of the net.\n\nTHE J-CURVE: fees and write-downs come first, exits come years later, so reported returns are NEGATIVE early and only climb afterwards. Judge private capital by IRR and MOIC (multiple of invested capital), not by an annual return, and remember IRR is sensitive to the timing of drawdowns the GP controls.\n\nTHE LOCK. Lock-up periods, notice periods, gates and side pockets mean you cannot leave when you want. And because holdings are valued by appraisal rather than by the market, reported volatility is SMOOTHED and correlations with public markets are UNDERSTATED — so the diversification looks better on paper than it is.",
      position: [-44.57, 4.02, -23.73],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#e8b168",
      labelPosition: [-44.57, 6.92, -23.73],
    },
    {
      id: 25,
      title: "Portfolio Management · The IPS",
      description: "A document on a stand: two objectives down the left, five padlocked constraints down the right.\n\nPORTFOLIO MANAGEMENT IS A PROCESS, not a stock pick. PLANNING (understand the client, write the Investment Policy Statement, set a strategic asset allocation) → EXECUTION (asset allocation, security analysis, construction) → FEEDBACK (monitor, rebalance, measure performance). The INVESTMENT POLICY STATEMENT is the contract with the client and the first thing to write.\n\nTHE TWO OBJECTIVES. RETURN — required versus desired, and stated in real, after-tax terms if that is how the client lives. RISK — two halves that must be reconciled: ABILITY to take risk (wealth, time horizon, liabilities — objective) and WILLINGNESS (temperament — subjective). When they conflict, the LOWER of the two governs, and the adviser educates rather than overrides.\n\nTHE FIVE CONSTRAINTS — TIME HORIZON, LIQUIDITY, TAXES, LEGAL AND REGULATORY, UNIQUE CIRCUMSTANCES.\n\nTHE PORTFOLIO PERSPECTIVE is the idea underneath all of it: judge an asset by what it does to the PORTFOLIO's risk and return, not on its own. A volatile asset with low correlation can REDUCE total risk — which is why the diversification ratio, not the individual standard deviation, is what matters.\n\nWHO INVESTS: individuals; DEFINED BENEFIT pensions (the sponsor bears the risk, liabilities are known, long horizon); defined contribution (the employee bears it); ENDOWMENTS and FOUNDATIONS (perpetual, spending-rate driven, high risk tolerance); BANKS (short horizon, liquidity-driven, low risk); INSURERS (life is long, property-casualty is short and liquidity-hungry); sovereign wealth funds.",
      position: [-5.94, 4.02, -50.64],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f2f2ee",
      labelPosition: [-5.94, 6.92, -50.64],
    },
    {
      id: 26,
      title: "Portfolio Management · The frontier, the line and beta",
      description: "A curve rising and flattening, a straight rod lifting off a risk-free base and touching it at one point, and a dial.\n\nDIVERSIFICATION. Portfolio return is the weighted average of the parts; portfolio RISK is not, because of covariance. The benefit rises as CORRELATION falls: at ρ = +1 there is none, at ρ < 1 the curve bows, at ρ = −1 risk can be eliminated entirely. Adding securities kills unsystematic (firm-specific) risk and leaves SYSTEMATIC (market) risk behind, which no amount of diversification removes.\n\nTHE EFFICIENT FRONTIER — the teal curve: every portfolio offering the highest return for its level of risk. Its left-hand tip is the global minimum-variance portfolio; nothing above the curve exists and nothing below it is worth owning.\n\nTHE CAPITAL ALLOCATION LINE — the gold rod: add a risk-free asset and you can lend (sit between the two) or borrow (go past the tangency point). The line that touches the frontier at the OPTIMAL RISKY PORTFOLIO dominates the curve everywhere, and its slope is the SHARPE RATIO. When everyone holds the same optimal risky portfolio, it is the MARKET portfolio and the line becomes the CAPITAL MARKET LINE. Where you sit on it is set by your own risk aversion — your indifference curves.\n\nCAPM, the dial: E(Ri) = Rf + βi[E(Rm) − Rf], with β = Cov(i, m) / Var(m). The claim is that only SYSTEMATIC risk is compensated, because the rest was free to diversify away. Plot it against beta and you get the SECURITY MARKET LINE: above the line is undervalued, below it is overvalued. Its assumptions (one period, homogeneous expectations, frictionless markets, unlimited risk-free borrowing) are all false, and it is still the benchmark everything else is measured against. Judge results with SHARPE (total risk), TREYNOR (beta), M² and JENSEN'S ALPHA (return above what CAPM demanded).",
      position: [-15.45, 4.02, -47.55],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f2f2ee",
      labelPosition: [-15.45, 6.92, -47.55],
    },
    {
      id: 27,
      title: "Portfolio Management · Biases, risk and the machines",
      description: "A head with gears on one side and a heart on the other, a funnel that identifies then measures then manages, and a candlestick chart with a small robot reading it faster than you can.\n\nBEHAVIOURAL BIASES split in two, and the split is the point. COGNITIVE ERRORS are faults of reasoning — belief perseverance (conservatism, CONFIRMATION bias, representativeness, illusion of control, hindsight) and information processing (ANCHORING, mental accounting, framing, availability). Because they are errors of thinking, they can be MODERATED with better information, education and process. EMOTIONAL BIASES come from feeling — LOSS AVERSION (losses hurt about twice as much as gains please, so losers get held and winners sold), OVERCONFIDENCE (which shows up as overtrading), self-control, STATUS QUO, endowment, regret aversion. These usually cannot be argued away and must be ACCOMMODATED in the plan instead.\n\nRISK MANAGEMENT is a framework, not a number: set risk GOVERNANCE and a risk TOLERANCE at the top, budget it across the portfolio, then IDENTIFY, MEASURE and MODIFY exposures — the four responses being AVOID, ACCEPT, TRANSFER (insure, hedge with derivatives) and MITIGATE. Risk is not only volatility: liquidity, credit, operational, model and tail risk all belong in the funnel, and VaR tells you a threshold, never the size of the loss beyond it.\n\nTECHNICAL ANALYSIS assumes price and volume already contain the crowd's behaviour: trends, support and resistance, chart patterns, moving averages, RSI and MACD, relative strength, Elliott waves. It is a direct challenge to weak-form efficiency — see locus 16.\n\nFINTECH is the last module and the newest: big data (volume, velocity, variety, veracity), machine learning (supervised, unsupervised, deep learning — and OVERFITTING, the sin of learning the noise), algorithmic and high-frequency trading, robo-advisers, distributed ledgers and smart contracts, and RegTech. Then walk back out to the gate, or round the ring the other way.",
      position: [-24.96, 4.02, -44.46],
      anchorFrom: [0, 0, 0],
      anchorDistance: -8.6,
      eyeHeight: 0.8,
      labelColor: "#f2f2ee",
      labelPosition: [-24.96, 6.92, -44.46],
    },
  ],
};
