// The Glacier Deck — a timber sitting platform on a cobbled promontory at
// sunset, a gnarled pine leaning over it, and a crevassed glacier two hundred
// metres below running out to a snow range in the last of the light.
//
// This scene has NO LOCI, deliberately. It is a place to be in rather than a
// sequence to be walked: there are no memory pegs, no numbered badges and no
// tour, and the viewer drops the whole transport bar when `loci` is empty
// (see Viewer.start / Walkthrough's `empty` flag). Free move is the only mode
// — open it and look around. If it ever needs pegs, the objects are all there
// to hang them on: the setts, the gate, the lantern, the shelf of stacked
// cairns, the bonsai, the two cushions, the incense tray, the pine, the far
// rail, and the glacier, river and peak below.
//
// Recreated from a reference photograph: the camera projection was solved
// first, then the deck corners, the cushions and the lantern were
// back-projected from the photo into world coordinates, so `startView` below
// is the photograph's own framing. Everything is procedural — terrain,
// crevasse field, wood grain, cobbles, needles — generated by
// blender_models/scenegen_glacierdeck/ (gd_*.py) through Blender MCP into
// blender_models/GlacierDeck.blend.
//
// Sibling room: [[meditation-ledge]] is the same instinct at dawn above a sea
// of cloud, and that one IS a tour — ten stops that double as the stations of
// a sit. This one is deliberately a different room in every way: sunset not
// dawn, ice not cloud, and nothing to walk between.
//
// Depth note: the landscape is authored at true scale and runs to 16 km, but
// the viewer's far plane is 2000. The exporter compresses depth radially about
// the hero eye (see scripts/glacier_deck_export.py), which leaves the opening
// view untouched but puts the peak at ~440 units instead of ~2.3 km.
export default {
  startView: {
    position: [0.61, 7.35, 15.25],
    lookAt: [0.35, 2.6, 0.0],
  },
  background: 0xdcb488,
  fog: { near: 40, far: 900 },
  // The viewer's sun is a fixed overhead white light, so the warmth of the
  // Blender sunset has to come from the ambient term instead: a strong warm
  // ambient with the blue hemisphere pulled well down, or the whole valley
  // reads as an overcast noon.
  lighting: {
    hemisphere: 0.5,
    ambient: 0.8,
    ambientColor: 0xffc890,
    sun: 1.5,
    shadowExtent: 22,
  },
  loci: [],
};
