// The Glacier Deck — a timber sitting platform on a cobbled promontory at
// sunset, a gnarled pine leaning over it, and a crevassed glacier two hundred
// metres below running out to a snow range in the last of the light.
//
// Recreated from a reference photograph: the camera projection was solved
// first, then the deck corners, the cushions and the lantern were
// back-projected from the photo into world coordinates, so the hero framing
// below is the photograph's framing. Everything is procedural — terrain,
// crevasse field, wood grain, cobbles, needles — generated by
// blender_models/scenegen_glacierdeck/ (gd_*.py) through Blender MCP into
// blender_models/GlacierDeck.blend.
//
// Sibling room: [[meditation-ledge]] is the same instinct at dawn above a sea
// of cloud. This one is deliberately a different room — sunset not dawn, ice
// not cloud, a cobbled approach and a shelf of cairns instead of a gate and a
// basin — so the two don't blur together in memory.
//
// The rig follows the Ledge's: every locus names `anchorFrom: [0, 0, 0]` (the
// deck centre, which scripts/glacier_deck_export.py moves onto the origin)
// with a negative anchorDistance, so the camera always stands ON the deck and
// looks outward — including for the three loci that are hundreds of metres
// out over the ice.
//
// Depth note: the landscape is authored at true scale and runs to 16 km, but
// the viewer's far plane is 2000. The exporter compresses depth radially about
// the hero eye (see glacier_deck_export.py), which leaves the hero view
// untouched but puts the peak at ~440 units instead of ~2.3 km. The positions
// below are post-compression three.js space and are only fallbacks — the real
// ones are the Locus_01..12 empties baked into models/glacier-deck.glb.
//
// EMPTY PALACE: every peg is still blank. The titles name the object and the
// descriptions say what each is shaped to hold. Replace them when there is
// real content to attach.
export default {
  startView: {
    position: [0.61, 7.35, 15.25],
    lookAt: [0.35, 2.6, 0.0],
  },
  background: 0xdcb488,
  fog: { near: 40, far: 900 },
  // The viewer's sun is a fixed overhead white light, so the warmth of the
  // Blender sunset has to come from the ambient term instead: a strong warm
  // ambient with the blue hemisphere pulled well down, or the whole valley
  // reads as an overcast noon.
  lighting: {
    hemisphere: 0.5,
    ambient: 0.8,
    ambientColor: 0xffc890,
    sun: 1.5,
    shadowExtent: 22,
  },
  walkthrough: {
    travelSeconds: 6,
    dwellSeconds: 11,
    eyeHeight: 1.4,
    anchorDistance: -3.2,
    loop: true,
  },
  loci: [
    {
      id: 1,
      title: 'The Setts',
      description:
        'The cobbled apron in front of the deck: a few hundred hand-laid stones, no two the same size, moss in the joints. The approach, and the only part of the room you walk on rather than sit on. Good for anything made of many small similar units that only means something in aggregate — a corpus, a population, a long list you will never recall item by item.',
      position: [0.26, 0.12, 5.45],
      anchorFrom: [0, 0, 0],
      anchorDistance: -3.2,
      eyeHeight: 1.8,
    },
    {
      id: 2,
      title: 'The Gate',
      description:
        'A slatted timber gate in the right-hand rail, hung on a heavy post and standing a few degrees open. It is the only way on or off. Reserve it for a condition of entry: the thing that has to be true before the rest applies.',
      position: [2.16, 1.5, 1.58],
      anchorFrom: [0, 0, 0],
      anchorDistance: -3.0,
      eyeHeight: 0.4,
    },
    {
      id: 3,
      title: 'The Lantern',
      description:
        'A small brass-and-glass lantern on a low side table by the rail, already lit while there is still light in the sky. The one thing in the room that makes its own light. Use it for the item that has to stay lit when everything else goes dark — the invariant, the fallback, the thing you check first.',
      position: [1.98, 1.15, -1.49],
      anchorFrom: [0, 0, 0],
      anchorDistance: -3.0,
      eyeHeight: 0.75,
    },
    {
      id: 4,
      title: 'The Cairn Shelf',
      description:
        'An open timber rack along the left edge, three shelves deep, carrying four stacks of flat river stones balanced largest to smallest. Stacks of known height, in a frame with named slots: good for an ordered set you need to be able to count, or for a hierarchy that narrows as it rises.',
      position: [-1.15, 1.0, -1.17],
      anchorFrom: [0, 0, 0],
      anchorDistance: -3.2,
      eyeHeight: 0.9,
    },
    {
      id: 5,
      title: 'The Bonsai',
      description:
        'A small pine in a terracotta pot on top of the shelf, the same species as the giant leaning over the deck, kept to thirty centimetres. The whole thing in miniature. Anchor for a model, a scaled-down case, or the toy example that stands in for the real one.',
      position: [-0.6, 1.71, -1.1],
      anchorFrom: [0, 0, 0],
      anchorDistance: -2.8,
      eyeHeight: 0.2,
    },
    {
      id: 6,
      title: 'The Two Cushions',
      description:
        'Two round linen zafu on the planks, one slightly behind the other, so this is a room for two and not one. The seat. Good for a pair that belongs together but is not symmetrical — a dialogue, a comparison, a before and after.',
      position: [0.67, 0.85, -0.98],
      anchorFrom: [0, 0, 6],
      anchorDistance: -3.4,
      eyeHeight: 1.05,
    },
    {
      id: 7,
      title: 'The Incense Tray',
      description:
        'A shallow wooden tray between the cushions with a ceramic burner and a single stick standing in it. It measures the sitting by burning down. Use it for anything that is spent as it is used — a budget, a deadline, a quantity that only decreases.',
      position: [0.6, 0.69, 0.01],
      anchorFrom: [0, 0, 6],
      anchorDistance: -2.6,
      eyeHeight: 1.0,
    },
    {
      id: 8,
      title: 'The Leaning Pine',
      description:
        'A gnarled pine growing out of the rock at the left of the platform, thirteen metres of trunk with almost all of its needle pads on the downwind side, reaching out over the deck. Everything it has, it put on one side. Anchor for a lopsided thing: the distribution with one long tail, the argument that only works in one direction.',
      position: [-2.19, 6.1, -0.95],
      anchorFrom: [0, 0, 0],
      anchorDistance: -5.2,
      eyeHeight: -4.2,
    },
    {
      id: 9,
      title: 'The Far Rail',
      description:
        'The back edge of the deck, where the planks stop and the promontory drops two hundred metres to the ice. Nothing is built past this point. Use it for a boundary: the limit of a claim, the last case before something breaks.',
      position: [0.29, 0.8, -2.4],
      anchorFrom: [0, 0, 0],
      anchorDistance: -5.0,
      eyeHeight: 1.1,
      // The last three stops park the camera on this spot, which would put a
      // full-size badge a handspan from the lens; shrink and lower it.
      labelScale: 0.55,
      labelOffsetY: 0.95,
    },
    {
      id: 10,
      title: 'The Glacier',
      description:
        'The ice field below and beyond the drop, its whole surface ruled across by crevasses — parallel, curving, and cut deepest where the ice bends. A single slow body that fractures wherever it is made to turn. Good for a large, coherent thing whose failures all lie in one direction.',
      position: [28.52, -70.39, -252.16],
      anchorFrom: [0, 0, 0],
      anchorDistance: -252.0,
      eyeHeight: 72.4,
      labelScale: 13,
      labelOffsetY: 18,
    },
    {
      id: 11,
      title: 'The River',
      description:
        'A thin pale thread of meltwater winding along the floor of the gorge to the left, three hundred metres down and still moving. The smallest visible thing in the room and the only one going anywhere. Reserve it for a slow process that will outlast everything above it.',
      position: [-31.45, -93.86, -279.14],
      anchorFrom: [0, 0, 0],
      anchorDistance: -279.1,
      eyeHeight: 95.9,
      labelScale: 15,
      labelOffsetY: 20,
    },
    {
      id: 12,
      title: 'The Sunset Peak',
      description:
        'The snow summit on the right of the valley, the furthest thing in the room and the last one holding the light. Reserve it for the goal — what the whole sequence is for, seen from the place you are actually sitting.',
      position: [77.42, -13.54, -435.73],
      anchorFrom: [0, 0, 0],
      anchorDistance: -440.7,
      eyeHeight: 15.5,
      labelScale: 22,
      labelOffsetY: 30,
    },
  ],
};
