// River of Time — key moments in the history of India, 2600 BCE to 1950.
//
// A low-poly valley: a serpentine road runs beside a river from the start
// tablet, past 25 plateaus in chronological order, each holding a numbered
// sign (year / event / detail) and a monument built as the memory peg — the
// Great Bath for the Indus Valley, a peacock (mayura) for the Mauryas, a giant
// golden zero for the Guptas, Babur's cannon, Gandhi's glasses. Six coloured
// era gates arch over the road where a new era begins, and each plateau's rim
// wears its era's colour, so the era is legible at a glance:
//   1-3    Ancient Roots          c. 2600 - 500 BCE   terracotta
//   4-8    Age of Empires         326 BCE - 606 CE    gold
//   9-13   Kingdoms & Sultans     712 - 1336          teal
//   14-19  Mughals & Merchants    1498 - 1674         plum
//   20-22  Company & Crown        1757 - 1885         red
//   23-25  Freedom & Republic     1930 - 1950         saffron
// The road hairpins twice, so the three rows read like lines of a page:
// ancient (1-8) along the front, medieval and Mughal (9-17) back the other way,
// colonial to Republic (18-25) along the foot of the mountains.
//
// Source: blender_models/IndiaHistory.blend, generated by
// blender_models/india_history_scenegen/ih_*.py. Locus_01..25 are baked into
// the .blend (children of Station_NN, on each monument's aim point — mid-height
// for the tall ones), so build_glb.py's SCENES entry is empty; export prep is in
// scripts/india_history_export.py, which also RECENTRES the scene by Blender
// (95, 72). Every number below is in that recentred three.js space.
//
// Camera: each locus carries its own anchorFrom — the point across the road,
// over the riverbank, that the Blender Cam_Tour uses — with a NEGATIVE
// anchorDistance equal to its horizontal distance, so the rig parks exactly
// there (see Walkthrough.js). The sign sits to the left of each monument so both
// are in frame. Tall monuments (Ashoka's pillar, the Chola temple, Qutub Minar)
// are shot from further back.

export default {
  // Open high over the south-east corner with the whole valley in view.
  startView: {
    position: [120, 150, 192],
    lookAt: [0, 0, 10],
  },
  walkthrough: {
    travelSeconds: 5,
    dwellSeconds: 10,
    eyeHeight: 3.5,
    anchorDistance: -24,
    loop: true,
  },
  background: 0xbcdcf2,
  // The valley is ~370 m across; the default 60/220 fog would swallow the far
  // rows from the opening view.
  fog: { near: 180, far: 650 },
  lighting: {
    hemisphere: 0.95,
    sun: 1.5,
    // Viewer's shadow box is centred on the origin; the export recentred the
    // scene there, and 195 covers the whole footprint.
    shadowExtent: 195,
    // Gold finials, bronze helmet and cannon read as black holes without it.
    environment: true,
    environmentIntensity: 0.55,
  },
  // Metre-scale scene with 6-20 m monuments: bigger badges, lifted per locus
  // (labelOffsetY) to float just above each monument's top.
  labels: { worldSize: 2.2, offsetY: 5 },
  loci: [
    {
      id: 1,
      title: "c. 2600 BCE — The Indus Valley Civilisation",
      description:
        "One of the world’s first great urban civilisations, along the Indus and its tributaries in what is now Pakistan and north-west India. Harappa and Mohenjo-daro had grid-planned streets, baked-brick houses, covered drains and standard weights — and a script nobody has yet deciphered. Here: the mud-brick citadel of Mohenjo-daro with its Great Bath, brick houses and a well, and a big clay seal like the thousands found there. (The stupa crowning the mound was added by Buddhists some 2,000 years later.)",
      position: [-81.0, 3.5, 60.0],
      anchorFrom: [-79.5, 0, 84.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 4.9,
    },
    {
      id: 2,
      title: "c. 1500 BCE — The Vedic Age",
      description:
        "Indo-Aryan-speaking peoples settle the north-west and compose the Rigveda, the oldest of the four Vedas, in Sanskrit. For centuries the hymns are memorised and chanted, not written. Religion centres on the fire sacrifice (yajna) to gods like Agni and Indra, and cattle are the measure of wealth. Here: the stepped brick fire altar between two sacrificial posts, a cow, a bundle of palm-leaf manuscript, and Om hanging over the flames.",
      position: [-60.0, 3.66, 60.0],
      anchorFrom: [-58.5, 0, 84.48],
      anchorDistance: -24.53,
      eyeHeight: 3.47,
      labelOffsetY: 6.36,
    },
    {
      id: 3,
      title: "c. 500 BCE — The Buddha and Mahavira",
      description:
        "Sixteen great kingdoms (the Mahajanapadas) crowd the Ganges plain, and new teachers question Vedic ritual. Siddhartha Gautama attains enlightenment under the Bodhi tree at Bodh Gaya and becomes the Buddha; Vardhamana Mahavira, the 24th tirthankara, gives Jainism its lasting shape and its core rule, ahimsa — non-violence. Here: the golden Buddha under the Bodhi tree, a Sanchi-style stupa on the right, and a white Jain shrine with its red flag on the left.",
      position: [-39.0, 4.62, 60.0],
      anchorFrom: [-37.5, 0, 87.36],
      anchorDistance: -27.4,
      eyeHeight: 3.28,
      labelOffsetY: 7.32,
    },
    {
      id: 4,
      title: "326 BCE — Alexander at the Hydaspes",
      description:
        "Alexander the Great crosses into the Punjab and beats King Porus at the Hydaspes (the Jhelum) despite Porus’ war elephants. Impressed, Alexander leaves him his kingdom — and soon after, his exhausted army refuses to march further east, and the Greeks turn back. Here: Porus’ war elephant facing a giant bronze Greek helmet, with a hoplite shield and long spears, and a strip of river behind.",
      position: [-18.0, 3.5, 60.0],
      anchorFrom: [-16.5, 0, 84.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 6.02,
    },
    {
      id: 5,
      title: "322 BCE — The Maurya Empire",
      description:
        "Chandragupta Maurya, guided by his minister Chanakya (Kautilya, author of the Arthashastra on statecraft), overthrows the Nanda kings of Magadha and founds the Maurya Empire — the first to cover most of the subcontinent, ruled from Pataliputra (Patna). Here: the golden throne with the crown on its cushion, Chanakya’s scroll on the lectern, and a peacock: mayura, the pun that makes ‘Maurya’ stick.",
      position: [3.0, 3.5, 60.0],
      anchorFrom: [4.5, 0, 84.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 4.0,
    },
    {
      id: 6,
      title: "261 BCE — The Kalinga War",
      description:
        "Chandragupta’s grandson Ashoka conquers Kalinga (Odisha). His own edict counts 100,000 killed and 150,000 carried off. Horrified, he turns to Buddhism and rules by dhamma — non-violence, tolerance, welfare — carving his edicts on rocks and pillars across the empire. Here: the polished pillar crowned by four lions and the dhamma wheel, with the broken sword laid down at its foot. The lion capital is India’s national emblem; the wheel is on its flag.",
      position: [24.0, 6.99, 60.0],
      anchorFrom: [25.5, 0, 94.45],
      anchorDistance: -34.48,
      eyeHeight: 2.8,
      labelOffsetY: 9.69,
    },
    {
      id: 7,
      title: "320 CE — The Gupta Golden Age",
      description:
        "Chandragupta I founds the Gupta Empire, remembered as India’s classical golden age. The decimal place-value system that will carry zero takes shape; Aryabhata (499 CE) puts π at 3.1416 and argues that the Earth spins on its axis; Kalidasa writes Shakuntala. Here: a giant golden zero, the rustless Iron Pillar cast in this era (it now stands in Delhi), a spinning globe with its orbit, and Kalidasa’s open book.",
      position: [45.0, 3.74, 60.0],
      anchorFrom: [46.5, 0, 84.73],
      anchorDistance: -24.78,
      eyeHeight: 3.45,
      labelOffsetY: 6.44,
    },
    {
      id: 8,
      title: "606 CE — Harsha and Nalanda",
      description:
        "Harsha becomes king and builds the last great empire of the north before the medieval kingdoms, ruling from Kannauj. Nalanda, the Buddhist monastery-university in Bihar, is at its height; the Chinese pilgrim Xuanzang studies there and describes Harsha’s court. Here: Nalanda’s terraced red-brick monastery with rows of cells, a stack of books for its famous library, Harsha’s royal parasol, and Xuanzang arriving with his pack of scrolls.",
      position: [66.0, 3.5, 60.0],
      anchorFrom: [67.5, 0, 84.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 5.55,
    },
    {
      id: 9,
      title: "712 CE — The Arabs reach Sindh",
      description:
        "Muhammad bin Qasim, a young Umayyad general, conquers Sindh and defeats Raja Dahir — the first Arab foothold in the subcontinent. Arab traders had long sailed these coasts, and it is along these routes that Indian numerals later travel west to become the ‘Arabic’ numerals. Here: an Arab dhow with its triangular lateen sail, moored in a lagoon between date palms.",
      position: [78.5, 3.8, 20.0],
      anchorFrom: [77.0, 0, -4.9],
      anchorDistance: -24.95,
      eyeHeight: 3.44,
      labelOffsetY: 6.5,
    },
    {
      id: 10,
      title: "1010 CE — The Chola Temple",
      description:
        "Rajaraja I of the Chola dynasty completes the Brihadeeswara Temple at Thanjavur, its 66 m granite tower one of the tallest structures of its day. The Cholas rule the south, and under his son Rajendra I their navies reach Sri Lanka and South-East Asia. Here: the stepped granite vimana with its golden finial, Nandi the bull facing the shrine, and a Chola bronze Nataraja — Shiva dancing in a ring of fire.",
      position: [57.5, 7.39, 20.0],
      anchorFrom: [56.0, 0, -15.67],
      anchorDistance: -35.7,
      eyeHeight: 2.72,
      labelOffsetY: 10.09,
    },
    {
      id: 11,
      title: "1192 — The Second Battle of Tarain",
      description:
        "Muhammad of Ghor, beaten by Prithviraj Chauhan at Tarain the year before, comes back and wins. Prithviraj is captured and killed, and the road to Delhi opens to Turkic rule in north India. Here: two swords crossed in a battlefield mound — the saffron-hilted Rajput blade and the green-hilted Ghurid one — with Prithviraj’s saffron banner falling and Ghori’s green banner standing.",
      position: [36.5, 3.84, 20.0],
      anchorFrom: [35.0, 0, -5.03],
      anchorDistance: -25.07,
      eyeHeight: 3.44,
      labelOffsetY: 6.55,
    },
    {
      id: 12,
      title: "1206 — The Delhi Sultanate",
      description:
        "After Ghori’s death his general Qutb-ud-din Aibak, a former slave, rules from Delhi and founds the Delhi Sultanate. Five dynasties will hold it for 320 years, until 1526. Aibak begins the Qutub Minar; his successor Iltutmish finishes it. Here: the fluted Qutub Minar — red sandstone below, white marble above from a later repair — beside the ruined arches and columns of the Quwwat-ul-Islam mosque.",
      position: [15.5, 9.5, 20.0],
      anchorFrom: [14.0, 0, -22.0],
      anchorDistance: -42.03,
      eyeHeight: 2.3,
      labelOffsetY: 12.2,
    },
    {
      id: 13,
      title: "1336 — The Vijayanagara Empire",
      description:
        "The brothers Harihara and Bukka found Vijayanagara in the Deccan. It becomes the great power of the south until its defeat at Talikota in 1565, and its capital Hampi, among boulder hills on the Tungabhadra, is one of the largest cities in the world. Here: Hampi’s famous stone chariot, drawn by two stone elephants, among giant granite boulders.",
      position: [-5.5, 3.5, 20.0],
      anchorFrom: [-7.0, 0, -4.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 5.48,
    },
    {
      id: 14,
      title: "1498 — Vasco da Gama reaches Calicut",
      description:
        "The Portuguese navigator sails round Africa and lands near Calicut on the Malabar coast — the first sea route from Europe to India. Pepper and spices draw in the Portuguese, then the Dutch, English and French; Portugal keeps Goa until 1961. Here: a caravel with the red cross on its sails, and sacks and heaps of black pepper on the shore.",
      position: [-26.5, 4.05, 20.0],
      anchorFrom: [-28.0, 0, -5.65],
      anchorDistance: -25.69,
      eyeHeight: 3.39,
      labelOffsetY: 6.75,
    },
    {
      id: 15,
      title: "1526 — The First Battle of Panipat",
      description:
        "Babur, a Timurid prince from Central Asia, defeats Ibrahim Lodi, the last Delhi Sultan, at Panipat — his field guns and cavalry tactics beating a far larger army — and founds the Mughal Empire. Here: Babur’s bronze cannon on its carriage, a pyramid of cannonballs, his camp tent and his green banner.",
      position: [-47.5, 3.5, 20.0],
      anchorFrom: [-49.0, 0, -4.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 5.2,
    },
    {
      id: 16,
      title: "1556 — Akbar the Great",
      description:
        "Akbar takes the throne at 13, and his regent wins the Second Battle of Panipat the same year. Over nearly fifty years he builds a centralised empire with a famously tolerant court — abolishing the jizya tax on non-Muslims and hosting debates between faiths. His new city, Fatehpur Sikri, gets the Buland Darwaza, the ‘Gate of Magnificence’. Here: that gateway, in red sandstone outlined with white marble.",
      position: [-68.5, 6.03, 20.0],
      anchorFrom: [-70.0, 0, -11.58],
      anchorDistance: -31.62,
      eyeHeight: 2.99,
      labelOffsetY: 8.72,
    },
    {
      id: 17,
      title: "1600 — The East India Company",
      description:
        "On 31 December 1600 Queen Elizabeth I charters a company of London merchants to trade in the East Indies. It comes for pepper, then cotton cloth, silk, indigo and tea — and within 160 years it is ruling territory. Here: crates stamped EIC, barrels, the Company’s striped flag with the red cross of St George, and the royal charter with its wax seal.",
      position: [-89.5, 4.5, 20.0],
      anchorFrom: [-91.0, 0, -7.0],
      anchorDistance: -27.04,
      eyeHeight: 3.3,
      labelOffsetY: 7.2,
    },
    {
      id: 18,
      title: "1653 — The Taj Mahal",
      description:
        "Shah Jahan, Akbar’s grandson, builds the Taj Mahal at Agra as a tomb for his wife Mumtaz Mahal, who died in 1631. Work runs from 1632 to about 1653; its white marble is inlaid with semi-precious stones, and the Mughal Empire is at its richest. Here: the onion dome, four minarets and the reflecting pool lined with cypresses.",
      position: [-81.0, 5.1, -68.0],
      anchorFrom: [-79.5, 0, -39.2],
      anchorDistance: -28.84,
      eyeHeight: 3.18,
      labelOffsetY: 7.8,
    },
    {
      id: 19,
      title: "1674 — Shivaji is crowned",
      description:
        "Shivaji, who carved out a Maratha kingdom from hill forts in the Western Ghats with fast guerrilla war against Bijapur and Aurangzeb’s Mughals, is crowned Chhatrapati at Raigad fort. In the next century the Marathas become the leading power in India. Here: a hill fort on dark basalt, the saffron swallow-tailed flag (bhagwa dhwaj), and the crown and sword before its gate.",
      position: [-60.0, 5.1, -68.0],
      anchorFrom: [-58.5, 0, -39.2],
      anchorDistance: -28.84,
      eyeHeight: 3.18,
      labelOffsetY: 7.8,
    },
    {
      id: 20,
      title: "1757 — The Battle of Plassey",
      description:
        "At Plassey in Bengal, the East India Company under Robert Clive defeats Nawab Siraj-ud-Daulah, whose commander Mir Jafar has been bought off and holds his troops back. The Company becomes the power behind Bengal’s throne — the start of British rule. The battle was fought around a mango grove. Here: the mango trees, a Company fort flying a red ensign, and a giant redcoat.",
      position: [-39.0, 3.5, -68.0],
      anchorFrom: [-37.5, 0, -44.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 5.2,
    },
    {
      id: 21,
      title: "1857 — The Revolt of 1857",
      description:
        "Sepoys at Meerut rise against the Company, and the revolt spreads to Delhi, Kanpur, Lucknow and Jhansi, with leaders such as Rani Lakshmibai and the old Mughal emperor Bahadur Shah Zafar. The spark: rumours that new rifle cartridges were greased with cow and pig fat. Crushed by 1858, it ends Company rule — the British Crown takes India over directly (the Raj). Here: the greased cartridge, a war drum with rifle and sword, fires across the north, and chapatis, passed village to village before the rising.",
      position: [-18.0, 3.5, -68.0],
      anchorFrom: [-16.5, 0, -44.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 5.6,
    },
    {
      id: 22,
      title: "1885 — The Indian National Congress",
      description:
        "Seventy-two delegates meet in Bombay to found the Indian National Congress, with W. C. Bonnerjee as its first president and the retired British official A. O. Hume among its founders. It begins by petitioning for a larger Indian voice in government and grows into the main vehicle of the freedom movement. Here: a columned hall with its name on the frieze, benches for the delegates, a lectern — and the number 72.",
      position: [3.0, 3.5, -68.0],
      anchorFrom: [4.5, 0, -44.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 5.0,
    },
    {
      id: 23,
      title: "1930 — The Salt March",
      description:
        "Gandhi walks about 385 km from Sabarmati Ashram to the sea at Dandi over 24 days and picks up a lump of natural salt, breaking the British salt tax. The civil disobedience that follows fills the jails and puts India’s cause before the world. Here: the salt heap by the sea, Gandhi’s round glasses and walking stick, the charkha spinning wheel, and a trail of footprints.",
      position: [24.0, 3.5, -68.0],
      anchorFrom: [25.5, 0, -44.0],
      anchorDistance: -24.05,
      eyeHeight: 3.5,
      labelOffsetY: 4.01,
    },
    {
      id: 24,
      title: "1947 — Independence and Partition",
      description:
        "At midnight on 14–15 August 1947 India becomes independent, with Jawaharlal Nehru as its first prime minister. The same moment brings Partition: British India splits into India and Pakistan, and 10–20 million people are uprooted amid terrible violence. Every Independence Day the prime minister raises the flag at the Red Fort in Delhi. Here: the Red Fort’s Lahori Gate, the tricolour, and a black crack running through the ground for Partition.",
      position: [45.0, 5.12, -68.0],
      anchorFrom: [46.5, 0, -39.16],
      anchorDistance: -28.88,
      eyeHeight: 3.17,
      labelOffsetY: 7.82,
    },
    {
      id: 25,
      title: "1950 — The Republic of India",
      description:
        "On 26 January 1950 the Constitution comes into force and India becomes a republic, with Rajendra Prasad as its first president. Drafted by a committee chaired by B. R. Ambedkar and adopted on 26 November 1949, it opens ‘We, the people of India’ and promises justice, liberty, equality and fraternity. Here: the Constitution open on its lectern, the Ashoka Chakra and two tricolours — 26 January is Republic Day.",
      position: [66.0, 3.64, -68.0],
      anchorFrom: [67.5, 0, -43.59],
      anchorDistance: -24.46,
      eyeHeight: 3.47,
      labelOffsetY: 6.34,
    },
  ],
};
