// The Nobel Medal Hall — the Nobel Prizes 2021–2025, all six prizes, 64
// laureates (counting organisations), on a low-poly plaza shaped like a gold medal lying on the water.
//
// Layout (Blender: blender_models/NobelHall.blend, built by
// blender_models/nobel_hall_scenegen/nh_*.py):
//   * centre: a giant standing Nobel medal on a pedestal, dynamite at its foot;
//   * six coloured paths run out like spokes, in the order of Nobel's will,
//     clockwise from the south: Physics (blue), Chemistry (green), Medicine
//     (red), Literature (purple), Peace (sky blue), Economics (amber);
//   * years grow OUTWARD like tree rings: every path has a plinth on each of
//     five gold rings (2021 innermost, 2025 outermost), alternating right/left
//     of the path, and an empty 2026 plinth at the rim;
//   * each plinth carries one low-poly memory peg (a globe with a fever for
//     climate models, a whale on a circus wagon for Krasznahorkai, a burger on
//     the NJ/PA state line for Card...) and a low tilted sign in front: year,
//     surnames, and a three-word 'for what'.
//
// Tour: 1 the medal; 2-31 the six wings, each walked outward 2021 -> 2025;
// 32 the empty 2026 plinth at the end of the Economics path.
//
// Locus_01..32 are baked into the .blend (collection 09_Loci), so
// build_glb.py's SCENES entry is empty; export prep is in
// scripts/nobel_hall_export.py. No recentring: the plaza is centred on the
// origin. Every number below is three.js space, metres. This file is generated
// from nh_layout.py (positions) — keep the two in step.
//
// Camera: every stop parks the camera exactly at anchorFrom (a negative
// anchorDistance = the horizontal distance to the locus), on the path's axis
// 6 m inside the plinth's ring, 0.65 m above the aim point: the peg fills the
// upper frame and the sign sits along the bottom edge. Badges take the wing's
// colour.

export default {
  // Open high over the south rim with the whole medal-plaza in view.
  startView: {
    position: [0, 58, 96],
    lookAt: [0, 0, -6],
  },
  walkthrough: {
    travelSeconds: 4.5,
    dwellSeconds: 14,
    eyeHeight: 0.65,
    anchorDistance: -6.46,
    loop: true,
  },
  background: 0xc4d9ea,
  fog: { near: 110, far: 340 },
  lighting: {
    hemisphere: 0.9,
    ambient: 0.2,
    ambientColor: 0xfff1dd,
    sun: 1.3,
    // The plaza is ~118 m across, centred on the origin.
    shadowExtent: 62,
    // The medal, the gold rings and the brass details need reflections to read.
    environment: true,
    environmentIntensity: 0.55,
    environmentColor: 0xe6ecf2,
  },
  labels: { worldSize: 0.5, offsetY: 2.2 },
  loci: [
    {
      id: 1,
      title: "Alfred Nobel’s medal — how this hall works",
      description: "Alfred Nobel (1833–1896) was a Swedish chemist and inventor who patented dynamite in 1867 (the red bundle by the pedestal) and grew rich making explosives. In his will, signed in Paris on 27 November 1895, he left most of his fortune to fund five prizes: Physics, Chemistry, Physiology or Medicine, Literature and Peace. They were first given in 1901. Economics was added later: Sweden’s central bank founded the ‘Prize in Economic Sciences in Memory of Alfred Nobel’ in 1968 and first awarded it in 1969. The prizes are handed out every 10 December, the day Nobel died; Peace in Oslo, all the others in Stockholm.\n\nHOW TO READ THIS HALL: six coloured paths run out from the medal in the order of the will, clockwise from the south: blue Physics, green Chemistry, red Medicine, purple Literature, sky-blue Peace, amber Economics. Years grow outward like tree rings: the first gold ring is 2021, the fifth is 2025, and the plinths alternate right, left, right, left, right. On each plinth stands one object that pictures the discovery; the sign in front gives the year, the surnames and what it was for. Walk each path outward, then cross the garden to the next.",
      position: [0, 3.3, 0],
      anchorFrom: [0, 0, 11],
      anchorDistance: -11,
      eyeHeight: 0.3,
      labelColor: "#c9a227",
      labelPosition: [0, 7.4, 0],
    },
    {
      id: 2,
      title: "2021 · Physics — Manabe, Hasselmann & Parisi",
      description: "Half to SYUKURO MANABE and KLAUS HASSELMANN “for the physical modelling of Earth’s climate, quantifying variability and reliably predicting global warming”; half to GIORGIO PARISI “for the discovery of the interplay of disorder and fluctuations in physical systems from atomic to planetary scales”.\n\nPEG: a globe with a thermometer running a fever — Manabe (in the 1960s the first computer models linking CO₂ to warming) and Hasselmann (who showed how to find the human fingerprint in noisy weather). Above it, a swirl of starlings: Parisi, the physicist of disorder, really did film the starling flocks over Rome to study how order emerges from chaos. Climate + chaos: the prize that said global warming is physics.",
      position: [-2.4, 2, 16],
      anchorFrom: [0, 0, 10],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#3b55d6",
    },
    {
      id: 3,
      title: "2022 · Physics — Aspect, Clauser & Zeilinger",
      description: "ALAIN ASPECT (France), JOHN F. CLAUSER (USA) and ANTON ZEILINGER (Austria) “for experiments with entangled photons, establishing the violation of Bell inequalities and pioneering quantum information science”.\n\nPEG: two glowing orbs tied by a twisted rope — two entangled photons. Measure one and the other ‘knows’: the white arrows always point opposite ways, however far apart the orbs are. Einstein called this ‘spooky action at a distance’; John Bell turned the argument into a test, and these three ran it — Clauser in 1972, Aspect in 1982 closing loopholes, Zeilinger teleporting quantum states. Their work is the root of quantum cryptography and quantum computing.",
      position: [2.4, 2, 23],
      anchorFrom: [0, 0, 17],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#3b55d6",
    },
    {
      id: 4,
      title: "2023 · Physics — Agostini, Krausz & L’Huillier",
      description: "PIERRE AGOSTINI, FERENC KRAUSZ and ANNE L’HUILLIER “for experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter”.\n\nPEG: a stopwatch struck by a lightning-bolt flash, freezing an electron mid-orbit (the little atom beside it). An attosecond is a billion-billionth of a second (10⁻¹⁸ s) — there are about as many attoseconds in one second as there have been seconds since the Big Bang. Flashes that short are the only ‘camera’ fast enough to catch electrons moving. L’Huillier (Lund) discovered the effect that makes them; Agostini and Krausz produced the first trains and single pulses. She was only the fifth woman to win the physics prize.",
      position: [-2.4, 2, 30],
      anchorFrom: [0, 0, 24],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#3b55d6",
    },
    {
      id: 5,
      title: "2024 · Physics — Hopfield & Hinton",
      description: "JOHN J. HOPFIELD and GEOFFREY HINTON “for foundational discoveries and inventions that enable machine learning with artificial neural networks”.\n\nPEG: a small neural network — three layers of glowing nodes wired together. Hopfield (1982) built a network that stores patterns and recalls a whole memory from a fragment, using the physics of atomic spins. Hinton built on it with the ‘Boltzmann machine’, which learns to recognise the characteristic features of its data, and went on to lead the deep-learning revolution behind today’s AI. HOPfield = memory that HOPs back; HINTon = the HINT that taught machines to learn. The year AI won the physics prize.",
      position: [2.4, 2, 37],
      anchorFrom: [0, 0, 31],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#3b55d6",
    },
    {
      id: 6,
      title: "2025 · Physics — Clarke, Devoret & Martinis",
      description: "JOHN CLARKE, MICHEL H. DEVORET and JOHN M. MARTINIS “for the discovery of macroscopic quantum mechanical tunnelling and energy quantisation in an electric circuit”.\n\nPEG: on a green circuit board, a ball stands in front of a brick wall — and its glowing twin is already on the other side, having tunnelled straight through. Behind them, a ladder with fixed rungs: energy can only sit on certain steps (quantisation). In 1984–85 at Berkeley, these three showed that a superconducting circuit big enough to hold in your hand behaves like a single quantum particle. That is the principle inside today’s superconducting quantum computers (Martinis later led Google’s).",
      position: [-2.4, 2, 44],
      anchorFrom: [0, 0, 38],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#3b55d6",
    },
    {
      id: 7,
      title: "2021 · Chemistry — List & MacMillan",
      description: "BENJAMIN LIST and DAVID W. C. MACMILLAN “for the development of asymmetric organocatalysis”.\n\nPEG: a pair of mirror-image hands holding up a small molecule. Many molecules come in left- and right-handed versions (chirality), and in a drug only one hand may work — the other can be useless or harmful. Chemists had only two kinds of catalyst: metals and enzymes. In 2000 List and MacMillan, working separately, showed a third: small, cheap ORGANIC molecules that build just one hand. Organo-catalysis = a little organic helper that picks the right hand.",
      position: [-15.06, 2, 5.92],
      anchorFrom: [-8.66, 0, 5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9e5b",
    },
    {
      id: 8,
      title: "2022 · Chemistry — Bertozzi, Meldal & Sharpless",
      description: "CAROLYN R. BERTOZZI, MORTEN MELDAL and K. BARRY SHARPLESS “for the development of click chemistry and bioorthogonal chemistry”.\n\nPEG: two building bricks about to snap together — CLICK! Sharpless and Meldal each found the copper-catalysed reaction that makes molecular building blocks buckle together quickly and cleanly, like a seat belt. Bertozzi then made click reactions that work inside living cells without disturbing them (‘bioorthogonal’), used to track molecules and target cancer drugs. It was Sharpless’s SECOND chemistry Nobel (the first was 2001).",
      position: [-18.72, 2, 13.58],
      anchorFrom: [-14.72, 0, 8.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9e5b",
    },
    {
      id: 9,
      title: "2023 · Chemistry — Bawendi, Brus & Ekimov",
      description: "MOUNGI G. BAWENDI, LOUIS E. BRUS and ALEXEI I. EKIMOV “for the discovery and synthesis of quantum dots”.\n\nPEG: a rack of five glowing vials, blue to red, each with a floating dot that grows as the colour warms. Quantum dots are nanocrystals so small that their SIZE decides their colour: tiny ones glow blue, bigger ones red. Ekimov (in coloured glass, 1981) and Brus (in liquid, 1983) discovered the effect; Bawendi (1993) learned to make perfect dots on demand. They light QLED TV screens and help surgeons see tumour tissue.",
      position: [-27.18, 2, 12.92],
      anchorFrom: [-20.78, 0, 12],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9e5b",
    },
    {
      id: 10,
      title: "2024 · Chemistry — Baker, Hassabis & Jumper",
      description: "Half to DAVID BAKER “for computational protein design”; half to DEMIS HASSABIS and JOHN M. JUMPER “for protein structure prediction”.\n\nPEG: a computer screen and, beside it, a coiled protein helix springing up. Proteins are chains of amino acids that fold into 3D shapes, and the shape is the function. Hassabis and Jumper (Google DeepMind) built AlphaFold2, the AI that predicts the shape of almost any protein from its sequence — a 50-year-old problem. Baker went the other way: he designs brand-new proteins that nature never made. Screen = the computer did the chemistry.",
      position: [-30.84, 2, 20.58],
      anchorFrom: [-26.85, 0, 15.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9e5b",
    },
    {
      id: 11,
      title: "2025 · Chemistry — Kitagawa, Robson & Yaghi",
      description: "SUSUMU KITAGAWA, RICHARD ROBSON and OMAR M. YAGHI “for the development of metal–organic frameworks”.\n\nPEG: a jungle-gym cage — metal nodes joined by struts — with glowing gas molecules caught inside. Metal–organic frameworks (MOFs) are crystals with enormous empty rooms: metal ions are the corners, long organic molecules the beams. A few grams can have the inner surface of a football pitch. They can pull water out of desert air, capture carbon dioxide, and store gases. Robson built the first in 1989; Kitagawa and Yaghi made them stable and flexible in the 1990s.",
      position: [-39.31, 2, 19.92],
      anchorFrom: [-32.91, 0, 19],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9e5b",
    },
    {
      id: 12,
      title: "2021 · Medicine — Julius & Patapoutian",
      description: "DAVID JULIUS and ARDEM PATAPOUTIAN “for their discoveries of receptors for temperature and touch”.\n\nPEG: a red-hot chili pepper, an ice cube, and a finger pressing a big red button. Julius used capsaicin — the burning compound in chili — to find TRPV1, the nerve sensor that reports heat; menthol led both men to the cold sensor. Patapoutian poked single cells with a tiny pipette to find PIEZO1 and PIEZO2, the sensors for pressure and touch (and for knowing where your own limbs are). Heat, cold, touch: how the body feels the world.",
      position: [-12.66, 2, -10.08],
      anchorFrom: [-8.66, 0, -5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#d0413a",
    },
    {
      id: 13,
      title: "2022 · Medicine — Pääbo",
      description: "SVANTE PÄÄBO “for his discoveries concerning the genomes of extinct hominins and human evolution”.\n\nPEG: a Neanderthal skull — long, low cranium and heavy brow ridge — with a strand of DNA spiralling beside it. Pääbo learned to read DNA from bones tens of thousands of years old, sequenced the Neanderthal genome (2010), and found a whole new kind of human, the Denisovans, from a single finger bone. Many people today carry 1–2 % Neanderthal DNA. He founded palaeogenomics. His father, Sune Bergström, won the same prize in 1982.",
      position: [-21.12, 2, -9.42],
      anchorFrom: [-14.72, 0, -8.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#d0413a",
    },
    {
      id: 14,
      title: "2023 · Medicine — Karikó & Weissman",
      description: "KATALIN KARIKÓ and DREW WEISSMAN “for their discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19”.\n\nPEG: a giant syringe of pink vaccine with a vial beside it and a purple mRNA strand drifting up. Injected mRNA used to trigger a harmful inflammation. In 2005 Karikó (a Hungarian biochemist long denied funding) and Weissman showed that swapping one of its letters for a slightly modified one (pseudouridine) lets it slip past the alarm. That tweak made the Pfizer-BioNTech and Moderna COVID-19 vaccines possible, given billions of times.",
      position: [-24.78, 2, -17.08],
      anchorFrom: [-20.78, 0, -12],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#d0413a",
    },
    {
      id: 15,
      title: "2024 · Medicine — Ambros & Ruvkun",
      description: "VICTOR AMBROS and GARY RUVKUN “for the discovery of microRNA and its role in post-transcriptional gene regulation”.\n\nPEG: a tiny worm in a glass dish — the 1-mm roundworm C. elegans — and a pair of scissors snipping a pink ribbon of messenger RNA. Studying that worm in 1993, the two found a very short RNA (lin-4) that switches a gene off by latching onto its messenger and stopping it being read — a whole new layer of gene control. (The scissors are the mnemonic; microRNAs mostly silence the message rather than cut it.) Humans have over a thousand microRNA genes.",
      position: [-33.24, 2, -16.42],
      anchorFrom: [-26.85, 0, -15.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#d0413a",
    },
    {
      id: 16,
      title: "2025 · Medicine — Brunkow, Ramsdell & Sakaguchi",
      description: "MARY E. BRUNKOW, FRED RAMSDELL and SHIMON SAKAGUCHI “for their discoveries concerning peripheral immune tolerance”.\n\nPEG: a blue cell in a police cap holding up a STOP sign, with small spiky red attacker cells held back behind it. That is a regulatory T cell (T-reg): the immune system’s own security guard that stops other immune cells from attacking the body. Sakaguchi found these cells in 1995; Brunkow and Ramsdell found the gene that controls them, FOXP3, in 2001 (in ‘scurfy’ mice). The discovery drives new treatments for autoimmune disease, cancer and transplants.",
      position: [-36.91, 2, -24.08],
      anchorFrom: [-32.91, 0, -19],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#d0413a",
    },
    {
      id: 17,
      title: "2021 · Literature — Gurnah",
      description: "ABDULRAZAK GURNAH (born in Zanzibar, 1948; lives in England) “for his uncompromising and compassionate penetration of the effects of colonialism and the fate of the refugee in the gulf between cultures and continents”.\n\nPEG: an Indian Ocean dhow under a triangular sail, with a suitcase on deck. Gurnah came to Britain as a refugee in the late 1960s, and his novels — Paradise (1994), By the Sea, Afterlives — follow people uprooted by empire and exile along the East African coast. Dhow + suitcase = the refugee between continents.",
      position: [2.4, 2, -16],
      anchorFrom: [0, 0, -10],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#8a4fc8",
    },
    {
      id: 18,
      title: "2022 · Literature — Ernaux",
      description: "ANNIE ERNAUX (France) “for the courage and clinical acuity with which she uncovers the roots, estrangements and collective restraints of personal memory”.\n\nPEG: a framed family photograph on an easel, a pile of loose old snapshots, and a box camera on a tripod. Ernaux writes memoir as if it were sociology, in flat, precise sentences; her masterpiece The Years (Les Années, 2008) tells sixty years of French life through descriptions of photographs of herself. Photos + camera = memory, recorded without flattery.",
      position: [-2.4, 2, -23],
      anchorFrom: [0, 0, -17],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#8a4fc8",
    },
    {
      id: 19,
      title: "2023 · Literature — Fosse",
      description: "JON FOSSE (Norway) “for his innovative plays and prose which give voice to the unsayable”.\n\nPEG: a small theatre stage with red curtains, a backdrop of fjord mountains under a moon, one empty chair — and three glowing dots floating in the air: the unsayable. Fosse is one of the world’s most-performed living playwrights; his spare, repetitive plays and his seven-part novel Septology, written in Nynorsk, live in the silences between words. Stage + fjord + ‘…’ = Fosse.",
      position: [2.4, 2, -30],
      anchorFrom: [0, 0, -24],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#8a4fc8",
    },
    {
      id: 20,
      title: "2024 · Literature — Han Kang",
      description: "HAN KANG (South Korea) “for her intense poetic prose that confronts historical traumas and exposes the fragility of human life”.\n\nPEG: a tree growing out of an open book, dropping pink petals on its pages. In The Vegetarian (2007; International Booker 2016) a woman stops eating meat and longs to become a plant; Human Acts (2014) returns to the 1980 Gwangju massacre. She is the first Korean — and first Asian woman — to win the literature prize. Book → tree = The Vegetarian.",
      position: [-2.4, 2, -37],
      anchorFrom: [0, 0, -31],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#8a4fc8",
    },
    {
      id: 21,
      title: "2025 · Literature — Krasznahorkai",
      description: "LÁSZLÓ KRASZNAHORKAI (Hungary) “for his compelling and visionary oeuvre that, in the midst of apocalyptic terror, reaffirms the power of art”.\n\nPEG: a giant stuffed whale riding on a striped circus wagon. In his novel The Melancholy of Resistance (1989) a shabby circus drags a huge dead whale into a small Hungarian town, and the town slides into chaos. His first novel, Satantango (1985), became a seven-hour film by Béla Tarr. Famous for sentences that run for pages. Whale on a wagon = apocalypse arrives in town.",
      position: [2.4, 2, -44],
      anchorFrom: [0, 0, -38],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#8a4fc8",
    },
    {
      id: 22,
      title: "2021 · Peace — Ressa & Muratov",
      description: "MARIA RESSA (the Philippines) and DMITRY MURATOV (Russia) “for their efforts to safeguard freedom of expression, which is a precondition for democracy and lasting peace”.\n\nPEG: an open newspaper reading PRESS / FREE, and a microphone. Both are journalists: Ressa co-founded the news site Rappler and exposed President Duterte’s drug war; Muratov co-founded the independent paper Novaya Gazeta, six of whose journalists were killed. In 2022 Muratov auctioned his medal for $103.5 million for Ukrainian refugee children. Newspaper + mic = the press must stay free.",
      position: [15.06, 2, -5.92],
      anchorFrom: [8.66, 0, -5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9fd8",
    },
    {
      id: 23,
      title: "2022 · Peace — Bialiatski, Memorial & Center for Civil Liberties",
      description: "ALES BIALIATSKI (Belarus), the Russian human-rights organisation MEMORIAL and the Ukrainian CENTER FOR CIVIL LIBERTIES — who “represent civil society in their home countries” and have “promoted the right to criticise power and protect the fundamental rights of citizens”.\n\nPEG: three columns holding up one roof, marked BY, RU and UA — civil society holding up the house in three neighbouring countries, awarded the year Russia invaded Ukraine. Bialiatski founded the human-rights group Viasna and was in prison when he won; Memorial, which documented Soviet repression, had been shut down by Russian courts; the Center for Civil Liberties records war crimes in Ukraine.",
      position: [18.72, 2, -13.58],
      anchorFrom: [14.72, 0, -8.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9fd8",
    },
    {
      id: 24,
      title: "2023 · Peace — Mohammadi",
      description: "NARGES MOHAMMADI (Iran) “for her fight against the oppression of women in Iran and her fight to promote human rights and freedom for all”.\n\nPEG: a prison window with one iron bar bent open, a white dove flying out, and a red flower at the foot of the wall. Mohammadi, a human-rights activist, won the prize while held in Tehran’s Evin prison; her teenage children accepted it for her in Oslo. It came a year after the ‘Woman, Life, Freedom’ protests that followed the death of Mahsa Amini in police custody.",
      position: [27.18, 2, -12.92],
      anchorFrom: [20.78, 0, -12],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9fd8",
    },
    {
      id: 25,
      title: "2024 · Peace — Nihon Hidankyo",
      description: "NIHON HIDANKYO, the Japan Confederation of A- and H-Bomb Sufferers Organizations, “for its efforts to achieve a world free of nuclear weapons and for demonstrating through witness testimony that nuclear weapons must never be used again”.\n\nPEG: a big folded paper crane. Nihon Hidankyo is the grassroots movement of the hibakusha, the survivors of Hiroshima and Nagasaki (1945), founded in 1956. The paper crane is their symbol: Sadako Sasaki, a girl who got leukaemia from the Hiroshima bomb, folded cranes hoping for a wish; children fold them for peace to this day.",
      position: [30.84, 2, -20.58],
      anchorFrom: [26.85, 0, -15.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9fd8",
    },
    {
      id: 26,
      title: "2025 · Peace — Machado",
      description: "MARÍA CORINA MACHADO (Venezuela) “for her tireless work promoting democratic rights for the people of Venezuela and for her struggle to achieve a just and peaceful transition from dictatorship to democracy”.\n\nPEG: a ballot box with a marked ballot going in (the yellow-blue-red band of Venezuela’s flag on its front) and a torch held high beside it. Machado, an engineer turned opposition leader, won the opposition primary but was barred from the 2024 presidential election; she backed a stand-in candidate, and the opposition gathered polling-station tally sheets to document the result. Ballot + torch = keeping democracy’s flame lit.",
      position: [39.31, 2, -19.92],
      anchorFrom: [32.91, 0, -19],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#2f9fd8",
    },
    {
      id: 27,
      title: "2021 · Economics — Card, Angrist & Imbens",
      description: "Half to DAVID CARD “for his empirical contributions to labour economics”; half to JOSHUA D. ANGRIST and GUIDO W. IMBENS “for their methodological contributions to the analysis of causal relationships”.\n\nPEG: a hamburger cut in two by a state line, NJ on one side, PA on the other. In 1992 New Jersey raised its minimum wage and neighbouring Pennsylvania did not; Card (with Alan Krueger) compared fast-food restaurants on either side and found no drop in jobs. That is a ‘natural experiment’: history runs the experiment for you. Angrist and Imbens worked out how to draw sound cause-and-effect conclusions from such accidents.",
      position: [12.66, 2, 10.08],
      anchorFrom: [8.66, 0, 5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#e09a1c",
    },
    {
      id: 28,
      title: "2022 · Economics — Bernanke, Diamond & Dybvig",
      description: "BEN S. BERNANKE, DOUGLAS W. DIAMOND and PHILIP H. DYBVIG “for research on banks and financial crises”.\n\nPEG: a pillared BANK with a nervous queue of people stretching out of its door — a bank run. Diamond and Dybvig (1983) showed why banks are useful and why that same design makes them fragile: if everyone fears everyone else will withdraw, all rush at once. Bernanke showed that bank failures turned the 1930 slump into the Great Depression — then, as chair of the US Federal Reserve, fought the 2008 crisis.",
      position: [21.12, 2, 9.42],
      anchorFrom: [14.72, 0, 8.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#e09a1c",
    },
    {
      id: 29,
      title: "2023 · Economics — Goldin",
      description: "CLAUDIA GOLDIN “for having advanced our understanding of women’s labour market outcomes”.\n\nPEG: a big golden U, with a working woman climbing its right-hand arm. Digging through 200 years of US records, Goldin found that married women’s work outside the home fell as the economy industrialised and then rose again with services and education — a U-shape, not a straight line up. She also showed how the contraceptive pill changed women’s careers and why the pay gap now opens mostly after the first child (‘greedy jobs’). Only the third woman to win it, and the first alone.",
      position: [24.78, 2, 17.08],
      anchorFrom: [20.78, 0, 12],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#e09a1c",
    },
    {
      id: 30,
      title: "2024 · Economics — Acemoglu, Johnson & Robinson",
      description: "DARON ACEMOGLU, SIMON JOHNSON and JAMES A. ROBINSON “for studies of how institutions are formed and affect prosperity”.\n\nPEG: one town split by a fence: tall, lit towers on the green side, small huts on the dusty side. Their favourite example is Nogales, a city cut in half by the US–Mexico border — same people, same climate, very different wealth. The difference is institutions: ‘inclusive’ rules (rights, courts, open markets) build prosperity, ‘extractive’ ones make a few rich. They traced it back to how colonisers ruled. Popular book: Why Nations Fail (2012).",
      position: [33.24, 2, 16.42],
      anchorFrom: [26.85, 0, 15.5],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#e09a1c",
    },
    {
      id: 31,
      title: "2025 · Economics — Mokyr, Aghion & Howitt",
      description: "Half to JOEL MOKYR “for having identified the prerequisites for sustained growth through technological progress”; half to PHILIPPE AGHION and PETER HOWITT “for the theory of sustained growth through creative destruction”.\n\nPEG: a glowing lightbulb rising on a shiny new gear out of the rubble of a broken old one, with a green arrow pointing up. Mokyr, an economic historian, showed that growth became sustained only after the Industrial Revolution, when useful science and practical know-how started feeding each other. Aghion and Howitt (1992) turned Schumpeter’s ‘creative destruction’ into a model: new ideas and firms keep replacing the old, and that churn is growth.",
      position: [36.91, 2, 24.08],
      anchorFrom: [32.91, 0, 19],
      anchorDistance: -6.46,
      eyeHeight: 0.65,
      labelColor: "#e09a1c",
    },
    {
      id: 32,
      title: "2026 — the empty plinths",
      description: "At the end of every path an empty glass plinth waits under a glowing question mark: the 2026 Nobel Prizes, announced in early October 2026. When they are, each new laureate gets the sixth ring of their wing, and this hall grows another year outward.\n\nREVIEW THE HALL: stand here and walk it back in your mind, wing by wing. Physics (blue): globe & starlings, entangled orbs, stopwatch flash, neural net, ball through a wall. Chemistry (green): mirror hands, click bricks, glowing vials, protein helix, MOF cage. Medicine (red): chili & button, Neanderthal skull, syringe, worm & scissors, police T-cell. Literature (purple): dhow, photographs, empty stage, tree from a book, whale on a wagon. Peace (sky blue): newspaper, three pillars, prison window, paper crane, ballot & torch. Economics (amber): burger on a state line, bank run, the U, divided town, lightbulb from rubble.",
      position: [44.17, 2, 25.5],
      anchorFrom: [38.97, 0, 22.5],
      anchorDistance: -6,
      eyeHeight: 0.65,
      labelColor: "#9aa3ad",
    },
  ],
};
