// The Stack — software engineering as one city, built as a round STEPPED PIT.
//
// Model: blender_models/TheStack.blend, generated by
// blender_models/stack_scenegen/st_*.py (st_build.build() → export()).
//
// THE ONE RULE THE SCENE ENCODES: ALTITUDE = ABSTRACTION. The pit floor is the
// machine; every terrace out and up is one layer further from it, ending on the
// rim, which is the organisation. Six concentric terraces:
//   -2 The Bedrock (indigo, z=0)    the machine
//   -1 The Mines (teal, z=15)       data structures & algorithms
//    0 The Artisans' Quarter (amber, z=30)   writing the code      [phase 2]
//   +1 The Grid (cyan, z=45)        systems & distributed systems  [phase 3]
//   +2 The Rim (green, z=60)        delivery & operations          [phase 4]
//    ^ The Summit (violet, z=74)    the antilibrary                [phase 5]
//
// Every district's content sits on the southern arc, 192°–348°. The northern
// 204° of every ring is left empty on purpose — THE UNBUILT QUARTER, pegged out
// for loci that don't exist yet. Districts run their arc in opposite directions
// so the tour spirals up, with a stairway at each turn.
//
// Camera: the pit is concentric, so every locus anchors from the pit axis
// (AXIS) with a NEGATIVE anchorDistance — the rig sits ~19 m inside the locus
// and looks outward at the prop with that district's riser wall, neon traces and
// nameplate behind it. Doors are set into the wall itself, so they stand off a
// little less.
//
// Phase 1 (this file): the pit + districts 1 and 2, loci 1–16.

const AXIS = [0, 0, 0];            // every terrace is concentric — one centre
const IND = '#6d7cff';             // -2 The Bedrock
const TEA = '#1fe3cf';             // -1 The Mines
const VIO = '#b478ff';             // the antilibrary doors

const D1 = { anchorFrom: AXIS, anchorDistance: -19, labelColor: IND };
const D2 = { anchorFrom: AXIS, anchorDistance: -19, labelColor: TEA };
const DOOR = { anchorFrom: AXIS, anchorDistance: -17, labelColor: VIO };

export default {
  walkthrough: {
    travelSeconds: 3.6,
    dwellSeconds: 13,
    eyeHeight: 2.2,
    anchorDistance: -19,
    loop: true,
  },
  // Night, and big: the pit is 320 m across, so the default 60/220 fog would
  // bury the far side of every terrace. The neon carries the colour; the lights
  // are turned down to let it.
  background: '#070a12',
  fog: { near: 95, far: 460 },
  lighting: {
    hemisphere: 0.42,
    ambient: 0.14,
    ambientColor: 0x9fb4ff,
    sun: 0.7,
    shadowExtent: 170,
  },
  loci: [
    {
      id: 1, ...D1, position: [-36.19, 3.0, 7.69],
      title: 'The Moth Case',
      description: `−2 THE BEDROCK. On 9 September 1947 operators at Harvard pulled a moth out of relay 70 of the Mark II and taped it into the logbook: "first actual case of bug being found". The word was already old — Edison used it in 1878 — but the tape made it ours. Start here, at the bottom of the city: the machine under you is simple and utterly literal. Every layer you climb through above it exists because people are not.`,
    },
    {
      id: 2, ...D1, position: [-26.97, 3.2, 25.33],
      title: 'The Gate',
      description: `A transistor is a switch: a voltage on the gate decides whether current crosses the channel. Wire a few into a NAND — the truth table in neon behind it — and you have a gate that is functionally complete: NAND alone can build every other operation, including memory. A modern processor is this, repeated tens of billions of times. There is nothing else underneath. Everything above is arrangement.`,
    },
    {
      id: 3, ...D1, position: [-9.95, 3.4, 35.64],
      title: 'The Foundry',
      description: `Fetch, decode, execute, write back — the loop the CPU runs billions of times a second. Like any assembly line it keeps every station busy at once: instruction four is being fetched while instruction one is still being written. That is pipelining, and it is Adam Smith's pin factory in silicon. It also explains the cost of a mispredicted branch: guess wrong about which way the code goes and the whole line has to be thrown away and refilled.`,
      link: 'pin-factory',
      linkLabel: 'The same idea in a pin factory →',
    },
    {
      id: 4, ...D1, position: [9.95, 3.2, 35.64],
      title: 'The Address Library',
      description: `Memory is a wall of numbered boxes and nothing more. A pointer is a slip of paper carrying a box number — not the thing, the location of the thing — which is why passing one is cheap and why a wrong number is catastrophic. Boxes that sit together travel together into cache, so walking memory in order can run ten times faster than hopping about it, even when both do the same amount of "work".`,
    },
    {
      id: 5, ...D1, position: [26.97, 3.6, 25.33],
      title: 'Stack Stair & Heap Yard',
      description: `Two ways to get memory. The stack is a pile of plates: every call pushes a frame, every return pops it, the order is guaranteed and the cleanup is free — until a recursion that never ends drives the plates into the ceiling (stack overflow). The heap is the open yard: any size, at any time, and it must be given back. A garbage collector makes the rounds in some languages; in others you do. What nobody frees and nobody uses is a leak.`,
    },
    {
      id: 6, ...DOOR, position: [41.86, 4.4, 8.9],
      title: 'The Halting Door — an open question',
      description: `Turing, 1936: no program can decide, for every program and input, whether it will ever stop. Not "we haven't worked it out yet" — it cannot exist. A surprising number of things you would like a tool to tell you are the halting problem in disguise, which is why every static analyser either misses real bugs or cries wolf, and always will. The first of the city's antilibrary doors: the wall where the method runs out.`,
    },
    {
      id: 7, ...D2, position: [57.71, 17.6, 12.27],
      title: 'The Mailbox Row',
      description: `−1 THE MINES. An array is boxes of equal size in a row, so box n is arithmetic — start plus n times size — and reaching it is instant. Its two costs: the row's length is fixed when it is built, and inserting into the middle shifts everything after it. Because neighbours are pulled into cache together, arrays beat cleverer structures far more often than the theory suggests.`,
    },
    {
      id: 8, ...D2, position: [51.44, 17.2, 28.9],
      title: 'The Barge Chain',
      description: `A linked list leaves each item wherever it landed and gives every item the address of the next. Splicing one in is two rewires — cheap. Finding the tenth means visiting nine, each a jump to somewhere unrelated in memory — dear. The last barge points at NULL, and dereferencing that null is the single most common crash in the trade; Tony Hoare, who introduced it in 1965, called it his billion-dollar mistake.`,
    },
    {
      id: 9, ...D2, position: [40.49, 18.0, 42.92],
      title: 'The Cloakroom',
      description: `A hash map turns the key into a hook number and walks straight to it, so lookup stays near-constant however big it gets. Two keys landing on one hook is a collision — ordinary, handled by hanging both and checking. It degrades in three ways: when the cloakroom fills (resize and rehash everything), when the hash is poor, and when an attacker can choose keys that all land on one hook, which is a denial-of-service, not a thought experiment.`,
    },
    {
      id: 10, ...D2, position: [25.86, 18.6, 53.03],
      title: 'The Orchard',
      description: `Keep things in order and every look can halve what is left. A binary search tree does that in memory. On disk a database index does it with a B-tree — the cabinet beside the orchard — where one drawer holds hundreds of keys, because fetching one key from a disk costs the same as fetching five hundred. An index is never free: every write has to update it too, which is why indexing everything makes a database slower, not faster.`,
    },
    {
      id: 11, ...D2, position: [8.89, 19.4, 58.33],
      title: 'The Metro Map',
      description: `A graph is things and the connections between them, and most real problems are graphs in disguise: dependencies, permissions, routes, call chains, friends. Two ways to search it — ring by ring (breadth-first, which finds the fewest hops) or down one line to its end and back (depth-first). Dijkstra worked out the shortest-path algorithm in about twenty minutes in an Amsterdam café in 1956, without pencil or paper, while his fiancée was shopping.`,
    },
    {
      id: 12, ...D2, position: [-8.89, 17.4, 58.33],
      title: 'The Hump Yard',
      description: `A railway hump yard is merge sort: push the wagons over the hump, sort them into sidings, then merge the sorted runs back into one train. Quicksort instead picks a pivot and throws everything smaller one way and larger the other — usually faster, quadratic when the pivot is chosen badly. Stability is whether two equal wagons keep the order they arrived in, and it matters the moment you sort by one thing and then another.`,
    },
    {
      id: 13, ...D2, position: [-25.86, 18.4, 53.03],
      title: 'Gradient Street',
      description: `Big-O is how the work grows as the input does, with the constants thrown away: flat O(1), the gentle O(log n), the straight climb O(n), the workhorse O(n log n), the steep O(n²) — and the sealed shaft O(n!), unusable past a dozen items. The thrown-away constants are real. An O(n log n) algorithm with a dreadful constant loses to a plain O(n²) one on small inputs every day of the week.`,
    },
    {
      id: 14, ...D2, position: [-40.49, 19.0, 42.92],
      title: 'The Hall of Mirrors',
      description: `A recursive function is written in terms of itself, and must have a door at the bottom: the base case, checked first, or the stack stair two levels down fills up. Anything recursive can be rewritten as a loop and the reverse, but tree-shaped problems read far better recursively. Write each answer on the wall as you get it (memoisation) and an exponential recursion collapses to a linear one — that is the whole of dynamic programming.`,
    },
    {
      id: 15, ...D2, position: [-51.44, 18.0, 28.9],
      title: 'The Lock Bridge',
      description: `One track, one bridge. A race condition is two trains on it at once — the same memory read and written by two threads, with the result decided by timing you do not control. A mutex is the toll gate. Deadlock is two trains nose to nose, each holding what the other needs. Therac-25, between 1985 and 1987, gave massive radiation overdoses through a race condition, which is why "it's only a timing bug" is not a sentence.`,
    },
    {
      id: 16, ...DOOR, position: [-63.38, 19.4, 13.47],
      title: 'The P vs NP Door — an open question',
      description: `Some problems are quick to check but appear to need a search to solve. If P = NP, every one of those searches has a shortcut nobody has found, and most of the cryptography holding up the modern world falls over. Fifty years on we cannot prove it either way — and worse, for almost no specific problem can we prove that no fast algorithm exists. The stair beyond this door climbs to the Artisans' Quarter.`,
    },
  ],
};
