// GENERATED by blender_models/office_scenegen/build_office.py -- do not edit.
//
// The Back Office sizes itself from the repo: the generator reads
// src/scenes/index.js for the registered scenes and every other
// src/scenes/*.js for `link:` edges, and gives a door to each scene that has
// no inbound edge. Re-run it after adding or wiring a scene and the corridor
// grows or shrinks a bay; src/scenes/the-office.js reads whatever is here.
//
// Built 19 doors out of 30 registered scenes, in 10 bays,
// corridor 29.4 m long.
export const BUILT = {
  scenes: 30,
  orphans: 19,
  bays: 10,
  corridorLength: 29.4,
};

export const WINGS = [
  {
    'name': 'The Subjects',
    'count': 4,
    'leaf': '#c2842f'
  },
  {
    'name': 'The Systems',
    'count': 4,
    'leaf': '#2c7a75'
  },
  {
    'name': 'Work & Worlds',
    'count': 4,
    'leaf': '#47569f'
  },
  {
    'name': 'The Quiet Rooms',
    'count': 4,
    'leaf': '#4c7742'
  },
  {
    'name': 'The New Wing',
    'count': 3,
    'leaf': '#6a4a8f'
  }
];

// Every stop, in tour order. `kind` is 'room' | 'door' | 'end'; a door stop
// also carries the scene it opens, the number painted beside its handle and
// the wing it belongs to. Positions are three.js space, straight off the
// Locus_NN empties in the glb.
export const LOCI = [
  {
    'id': 1,
    'kind': 'room',
    'position': [
      -2.95,
      1.0,
      6.5
    ],
    'anchorFrom': [
      0.0,
      0,
      4.5
    ],
    'anchorDistance': -3.0,
    'eyeHeight': 0.85
  },
  {
    'id': 2,
    'kind': 'room',
    'position': [
      -5.32,
      1.62,
      3.2
    ],
    'anchorFrom': [
      0.0,
      0,
      3.2
    ],
    'anchorDistance': -3.6,
    'eyeHeight': 0.25
  },
  {
    'id': 3,
    'kind': 'room',
    'position': [
      0.0,
      1.75,
      -0.3
    ],
    'anchorFrom': [
      0.0,
      0,
      6.0
    ],
    'anchorDistance': -7.0,
    'eyeHeight': 0.1
  },
  {
    'id': 4,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -2.4
    ],
    'anchorFrom': [
      0.0,
      0,
      -2.4
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 1,
    'scene': 'solar-system',
    'sceneTitle': 'The Solar System',
    'section': 'The Subjects',
    'color': '#c2842f'
  },
  {
    'id': 5,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -2.4
    ],
    'anchorFrom': [
      0.0,
      0,
      -2.4
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 2,
    'scene': 'india-history',
    'sceneTitle': 'River of Time: India',
    'section': 'The Subjects',
    'color': '#c2842f'
  },
  {
    'id': 6,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -5.1
    ],
    'anchorFrom': [
      0.0,
      0,
      -5.1
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 3,
    'scene': 'nobel-hall',
    'sceneTitle': 'The Nobel Medal Hall',
    'section': 'The Subjects',
    'color': '#c2842f'
  },
  {
    'id': 7,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -5.1
    ],
    'anchorFrom': [
      0.0,
      0,
      -5.1
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 4,
    'scene': 'cfa-level-1',
    'sceneTitle': 'The CFA Financial District',
    'section': 'The Subjects',
    'color': '#c2842f'
  },
  {
    'id': 8,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -7.8
    ],
    'anchorFrom': [
      0.0,
      0,
      -7.8
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 5,
    'scene': 'macro-hydraulic-hall',
    'sceneTitle': 'The Hydraulic Hall',
    'section': 'The Systems',
    'color': '#2c7a75'
  },
  {
    'id': 9,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -7.8
    ],
    'anchorFrom': [
      0.0,
      0,
      -7.8
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 6,
    'scene': 'the-stack',
    'sceneTitle': 'The Stack',
    'section': 'The Systems',
    'color': '#2c7a75'
  },
  {
    'id': 10,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -10.5
    ],
    'anchorFrom': [
      0.0,
      0,
      -10.5
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 7,
    'scene': 'body-heart',
    'sceneTitle': 'The Pump House',
    'section': 'The Systems',
    'color': '#2c7a75'
  },
  {
    'id': 11,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -10.5
    ],
    'anchorFrom': [
      0.0,
      0,
      -10.5
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 8,
    'scene': 'body-lungs',
    'sceneTitle': 'The Bellows Cathedral',
    'section': 'The Systems',
    'color': '#2c7a75'
  },
  {
    'id': 12,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -13.2
    ],
    'anchorFrom': [
      0.0,
      0,
      -13.2
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 9,
    'scene': 'grab-workplace',
    'sceneTitle': 'The Green Court',
    'section': 'Work & Worlds',
    'color': '#47569f'
  },
  {
    'id': 13,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -13.2
    ],
    'anchorFrom': [
      0.0,
      0,
      -13.2
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 10,
    'scene': 'lunar-base',
    'sceneTitle': 'Lunar Base',
    'section': 'Work & Worlds',
    'color': '#47569f'
  },
  {
    'id': 14,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -15.9
    ],
    'anchorFrom': [
      0.0,
      0,
      -15.9
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 11,
    'scene': 'future-city',
    'sceneTitle': 'Future City',
    'section': 'Work & Worlds',
    'color': '#47569f'
  },
  {
    'id': 15,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -15.9
    ],
    'anchorFrom': [
      0.0,
      0,
      -15.9
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 12,
    'scene': 'sky-loft',
    'sceneTitle': 'The Sky Loft',
    'section': 'Work & Worlds',
    'color': '#47569f'
  },
  {
    'id': 16,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -18.6
    ],
    'anchorFrom': [
      0.0,
      0,
      -18.6
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 13,
    'scene': 'hutong-corner',
    'sceneTitle': 'Hutong Corner',
    'section': 'The Quiet Rooms',
    'color': '#4c7742'
  },
  {
    'id': 17,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -18.6
    ],
    'anchorFrom': [
      0.0,
      0,
      -18.6
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 14,
    'scene': 'misty-valley',
    'sceneTitle': 'The Misty Valley',
    'section': 'The Quiet Rooms',
    'color': '#4c7742'
  },
  {
    'id': 18,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -21.3
    ],
    'anchorFrom': [
      0.0,
      0,
      -21.3
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 15,
    'scene': 'meditation-ledge',
    'sceneTitle': 'The Ledge',
    'section': 'The Quiet Rooms',
    'color': '#4c7742'
  },
  {
    'id': 19,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -21.3
    ],
    'anchorFrom': [
      0.0,
      0,
      -21.3
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 16,
    'scene': 'glacier-deck',
    'sceneTitle': 'The Glacier Deck',
    'section': 'The Quiet Rooms',
    'color': '#4c7742'
  },
  {
    'id': 20,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -24.0
    ],
    'anchorFrom': [
      0.0,
      0,
      -24.0
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 17,
    'scene': 'endless-survey',
    'sceneTitle': 'The Endless Survey',
    'section': 'The New Wing',
    'color': '#6a4a8f'
  },
  {
    'id': 21,
    'kind': 'door',
    'position': [
      2.84,
      1.75,
      -24.0
    ],
    'anchorFrom': [
      0.0,
      0,
      -24.0
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 18,
    'scene': 'cafef-vn',
    'sceneTitle': 'Sàn Bảng Điện',
    'section': 'The New Wing',
    'color': '#6a4a8f'
  },
  {
    'id': 22,
    'kind': 'door',
    'position': [
      -2.84,
      1.75,
      -26.7
    ],
    'anchorFrom': [
      0.0,
      0,
      -26.7
    ],
    'anchorDistance': -3.3,
    'eyeHeight': 0.15,
    'door': 19,
    'scene': 'tuoitre-vn',
    'sceneTitle': 'Phố Báo Sáng',
    'section': 'The New Wing',
    'color': '#6a4a8f'
  },
  {
    'id': 23,
    'kind': 'end',
    'position': [
      0.0,
      1.35,
      -29.1
    ],
    'anchorFrom': [
      0.0,
      0,
      -23.4
    ],
    'anchorDistance': -6.0,
    'eyeHeight': 0.35
  }
];

export const DOORS = LOCI.filter((l) => l.kind === 'door');
