// World War II: Theatre of War — 32 turning points of the Second World War,
// July 1937 to September 1945, on a low-poly war-room map table.
//
// Every event stands WHERE it happened: a hex plinth with a low-poly monument
// as its memory peg (a lightning bolt for Blitzkrieg, a literal torch for
// Operation Torch, a loaf of bread for besieged Leningrad, four red suns for the
// carriers lost at Midway, a white dove for the surrender) and a tilted sign
// with number, date and title. Glowing arcs join the stops in DATE order, so
// the tour jumps between Europe and the Pacific the way the war did. The front
// rim of the table carries a timeline ruler with every event at its date.
//
// Colour = year, on the plinth band, the sign badge, the path arc and the
// numbered badge:
//   1937-39 purple   1940 blue   1941 teal   1942 gold
//   1943 orange      1944 red    1945 pink
//
// The map projection is a smooth "fisheye": Europe, where most of the events
// cluster, is drawn larger than the Atlantic, Central Asia and the Pacific.
//
// Source: blender_models/WorldWarII.blend, generated by
// blender_models/ww2_scenegen/ww2_*.py. Locus_01..32 are baked into the .blend
// on each monument's aim point, so build_glb.py's SCENES entry is empty; export
// prep is in scripts/world_war_2_export.py, which SCALES the scene x5 (the .blend
// is authored ~82 units wide) and drops the Blender number medallions. Every
// number below is in that scaled three.js space.
//
// Camera: each locus parks the camera exactly at anchorFrom (negative
// anchorDistance = the horizontal distance), about 28 m out and 27 degrees up,
// from the south so the sign in front of the monument is in frame; stops whose
// sign sits to one side (2, 5, 6, 8, 16) are shot from that side.
//
// Badges: labelPosition puts each numbered badge exactly where the .blend's
// medallion was — on top of its brass pole, where the date-order arcs start and
// end — and labelColor tints it with the event's year colour.

export default {
  // Open high over the front edge of the table with the whole world in view.
  startView: {
    position: [0, 324, 248],
    lookAt: [0, 0, 13],
  },
  walkthrough: {
    travelSeconds: 6,
    dwellSeconds: 10,
    eyeHeight: 12.7,
    anchorDistance: -25,
    loop: true,
  },
  background: 0xb9c7d6,
  // The table is ~430 m across and the opening view sits ~400 m out.
  fog: { near: 450, far: 1300 },
  lighting: {
    hemisphere: 0.95,
    sun: 1.5,
    // Viewer's shadow box is centred on the origin; the map is centred there
    // and 230 covers the whole table.
    shadowExtent: 230,
    // Brass poles, gold spires and the sign rims need reflections to read.
    environment: true,
    environmentIntensity: 0.5,
  },
  labels: { worldSize: 2.8, offsetY: 6 },
  loci: [
    {
      id: 1,
      title: "7 Jul 1937 — Marco Polo Bridge",
      description:
        "A night-time clash between Japanese and Chinese troops at the Marco Polo Bridge (Lugou Bridge) outside Beijing escalates into full-scale war between Japan and China. For China the Second World War starts here, two years before Europe's: Shanghai and the capital, Nanjing, fall before the year is out. Here: the old stone bridge, famous for the hundreds of carved lions on its railings, with a Japanese tank crossing, a Chinese soldier holding the far end, and the flags of Japan and the Republic of China.",
      position: [119.85, 4.9, 9.16],
      anchorFrom: [119.85, 0, 34.11],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [122.33, 10.9, 6.41],
      labelColor: "#8a63c9",
    },
    {
      id: 2,
      title: "1 Sep 1939 — Invasion of Poland",
      description:
        "At dawn Germany invades Poland, after staging a fake 'Polish attack' on a border radio station the night before. Britain and France, pledged to defend Poland, declare war on Germany on 3 September: the war in Europe has begun. On 17 September the Soviet Union invades from the east under its secret pact with Hitler, and Poland is carved up between them. Here: a German tank bursting through a red-and-white striped border barrier, beside the white-and-red Polish flag.",
      position: [0.01, 5.02, -37.98],
      anchorFrom: [10.55, 0, -15.37],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [2.48, 11.02, -40.73],
      labelColor: "#8a63c9",
    },
    {
      id: 3,
      title: "30 Nov 1939 — Winter War",
      description:
        "The Soviet Union attacks Finland after it refuses to hand over land near Leningrad. Heavily outnumbered Finnish soldiers on skis, in white snow suits, fight the Red Army to a standstill through a brutal winter. Finland makes peace in March 1940, giving up about a tenth of its territory but keeping its independence, and the Red Army's poor showing is noted in Berlin. Here: a snowy hill of pines, a white-clad ski soldier, crossed skis and the blue-cross Finnish flag.",
      position: [22.99, 4.98, -73.43],
      anchorFrom: [22.99, 0, -48.48],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [25.46, 10.98, -76.18],
      labelColor: "#8a63c9",
    },
    {
      id: 4,
      title: "9 Apr 1940 — Denmark & Norway",
      description:
        "Germany strikes north to secure the Swedish iron ore shipped out through the Norwegian port of Narvik. Denmark surrenders within hours; Norway fights on for two months with British and French help while German warships and paratroopers seize its ports and airfields. The failed Allied campaign in Norway helps bring down Britain's Prime Minister, Neville Chamberlain. Here: snow-capped fjord peaks, a German warship in the fjord and a paratrooper drifting down.",
      position: [-53.88, 6.74, -70.42],
      anchorFrom: [-53.88, 0, -45.47],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-51.4, 12.74, -73.17],
      labelColor: "#3a63d8",
    },
    {
      id: 5,
      title: "10 May 1940 — Blitzkrieg in the West",
      description:
        "Germany invades the Netherlands, Belgium and Luxembourg, while its tanks push through the Ardennes forest, thought impassable, to cross the Meuse at Sedan and race for the English Channel. 'Blitzkrieg' means 'lightning war': tanks and dive-bombers moving too fast for the defence to react. The same day, Winston Churchill becomes Britain's Prime Minister. Here: a giant yellow lightning bolt over a German tank, with a Stuka dive-bomber overhead.",
      position: [-65.97, 4.9, -38.44],
      anchorFrom: [-55.43, 0, -15.83],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-63.5, 10.9, -41.19],
      labelColor: "#3a63d8",
    },
    {
      id: 6,
      title: "26 May 1940 — Dunkirk",
      description:
        "With the British and much of the French army trapped against the sea, Operation Dynamo evacuates them from the harbour and beaches of Dunkirk. Over nine days, destroyers and hundreds of 'little ships' (fishing boats, ferries, pleasure yachts) carry about 338,000 soldiers to England. The army's equipment is lost, but its men are saved to fight again. Here: soldiers waiting on the beach, a destroyer and a flotilla of small civilian boats, with smoke rising behind.",
      position: [-82.13, 4.92, -32.51],
      anchorFrom: [-96.44, 0, -12.07],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-79.65, 10.92, -35.26],
      labelColor: "#3a63d8",
    },
    {
      id: 7,
      title: "22 Jun 1940 — France Falls",
      description:
        "German troops enter Paris on 14 June, and on 22 June France signs an armistice at Compiègne, in the same railway carriage where Germany had surrendered in 1918, chosen by Hitler as revenge. Germany occupies the north and the Atlantic coast; the rest is run from Vichy by a collaborating government under Marshal Pétain, while General de Gaulle calls on the French to fight on from London. Here: the Eiffel Tower, a white flag of surrender and the French tricolour.",
      position: [-82.32, 4.96, -22.42],
      anchorFrom: [-82.32, 0, 2.53],
      anchorDistance: -24.95,
      eyeHeight: 12.72,
      labelPosition: [-79.85, 10.96, -25.17],
      labelColor: "#3a63d8",
    },
    {
      id: 8,
      title: "10 Jul 1940 — Battle of Britain",
      description:
        "The Luftwaffe tries to win control of the skies over southern England so that Germany can invade. RAF Fighter Command, flying Spitfires and Hurricanes and guided by radar, holds on through the summer. From September Germany switches to bombing London and other cities, the Blitz, and the invasion is postponed indefinitely: Hitler's first defeat. Churchill: 'Never in the field of human conflict was so much owed by so many to so few.' Here: Big Ben, a Spitfire with RAF roundels, and a German plane going down in smoke.",
      position: [-96.47, 4.9, -38.91],
      anchorFrom: [-107.01, 0, -16.29],
      anchorDistance: -24.96,
      eyeHeight: 12.71,
      labelPosition: [-93.99, 10.9, -41.66],
      labelColor: "#3a63d8",
    },
    {
      id: 9,
      title: "11 Mar 1941 — Lend-Lease",
      description:
        "The United States is still officially neutral, but Congress passes the Lend-Lease Act, letting President Roosevelt send weapons, food and fuel to Britain, and later to the Soviet Union, China and others, without cash payment. Roosevelt had called America the 'arsenal of democracy'; by 1945 Lend-Lease aid was worth about $50 billion. Here: the dome of the US Capitol, crates stamped with white stars, and a tank ready to ship.",
      position: [-178.89, 5.42, 11.37],
      anchorFrom: [-178.89, 0, 36.32],
      anchorDistance: -24.95,
      eyeHeight: 12.72,
      labelPosition: [-176.41, 11.42, 8.62],
      labelColor: "#16a394",
    },
    {
      id: 10,
      title: "22 Jun 1941 — Operation Barbarossa",
      description:
        "Breaking his pact with Stalin, Hitler invades the Soviet Union with some three million German troops on a front from the Baltic to the Black Sea, the largest invasion in history. It is named after the medieval emperor Frederick 'Red Beard' Barbarossa. It overruns vast areas and takes millions of prisoners, but fails to capture Moscow before winter. Here: a huge grey arrow driving east, flanked by tanks, with a plane overhead.",
      position: [13.75, 4.9, -30.49],
      anchorFrom: [13.75, 0, -5.54],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [16.23, 10.9, -33.24],
      labelColor: "#16a394",
    },
    {
      id: 11,
      title: "8 Sep 1941 — Siege of Leningrad",
      description:
        "German and Finnish forces cut Leningrad (St Petersburg) off from the rest of the Soviet Union. The siege lasts 872 days, until January 1944; the only lifeline is the 'Road of Life' across frozen Lake Ladoga. Around a million civilians die, most of them from starvation; at its worst the bread ration fell to 125 grams a day. Here: the golden spire of the Admiralty ringed by siege walls, and a single loaf of bread.",
      position: [32.25, 4.9, -67.53],
      anchorFrom: [32.25, 0, -42.58],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [34.73, 10.9, -70.28],
      labelColor: "#16a394",
    },
    {
      id: 12,
      title: "5 Dec 1941 — Battle of Moscow",
      description:
        "German armies reach within about 30 km of the Kremlin, but are slowed by autumn mud, then a savage winter, and meet fresh Soviet divisions brought from Siberia. On 5 December the Red Army counter-attacks and drives them back from the capital: the first major German defeat on land. Two days later comes Pearl Harbor (13). Here: the snowy onion domes of St Basil's Cathedral, the red Kremlin wall with its red star, and a white-painted Soviet tank.",
      position: [51.34, 4.94, -53.48],
      anchorFrom: [51.34, 0, -28.54],
      anchorDistance: -24.94,
      eyeHeight: 12.71,
      labelPosition: [53.81, 10.94, -56.23],
      labelColor: "#16a394",
    },
    {
      id: 13,
      title: "7 Dec 1941 — Pearl Harbor",
      description:
        "Japanese carrier planes make a surprise attack on the US Pacific Fleet at Pearl Harbor, Hawaii, sinking or damaging eight battleships and killing about 2,400 Americans. Roosevelt calls it 'a date which will live in infamy', and the US declares war on Japan the next day; on 11 December Germany and Italy declare war on the US. The war is now truly worldwide. Here: a burning, listing battleship with a column of black smoke, and a Japanese Zero fighter with red suns on its wings.",
      position: [196.29, 4.9, 42.75],
      anchorFrom: [196.29, 0, 67.7],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [198.76, 10.9, 40.0],
      labelColor: "#16a394",
    },
    {
      id: 14,
      title: "15 Feb 1942 — Fall of Singapore",
      description:
        "Japan sweeps across South-East Asia (Hong Kong, Malaya, the Philippines, the Dutch East Indies) and takes Singapore, Britain's great naval base, the 'Gibraltar of the East'. Its defences were built against an attack from the sea; the Japanese came overland instead, down the Malay peninsula behind them. About 80,000 British, Australian and Indian troops surrender, the largest surrender in British history. Here: the fortress with its big gun pointing out to sea, Japanese soldiers arriving from behind, and a white flag.",
      position: [108.53, 4.9, 67.65],
      anchorFrom: [108.53, 0, 92.6],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [111.01, 10.9, 64.9],
      labelColor: "#e8b21f",
    },
    {
      id: 15,
      title: "4 Jun 1942 — Midway",
      description:
        "Japan tries to lure the remaining American carriers into a trap near Midway atoll, but US codebreakers have read its plans. In a few minutes on the morning of 4 June, American dive-bombers wreck three Japanese carriers, and a fourth is sunk that afternoon; the US loses one, the Yorktown. Japan never replaces those carriers and pilots. Six months after Pearl Harbor, the Pacific war turns. Here: a burning carrier, a diving American bomber, and four red suns for the four carriers Japan lost.",
      position: [184.73, 4.9, 31.69],
      anchorFrom: [184.73, 0, 56.64],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [187.21, 10.9, 28.94],
      labelColor: "#e8b21f",
    },
    {
      id: 16,
      title: "7 Aug 1942 — Guadalcanal",
      description:
        "US Marines land on Guadalcanal in the Solomon Islands and seize the airfield Japan is building there: the first major Allied offensive against Japan. Six months of savage jungle fighting and night battles at sea follow, until Japan evacuates the island in February 1943. From here the Allies begin to climb back up the island chains towards Japan. Here: a palm island with the US flag, a landing craft on the beach and a Marine.",
      position: [171.2, 5.01, 80.56],
      anchorFrom: [185.51, 0, 101.0],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [173.67, 11.01, 77.81],
      labelColor: "#e8b21f",
    },
    {
      id: 17,
      title: "23 Aug 1942 — Stalingrad",
      description:
        "Germany's summer offensive drives for the Caucasus oilfields and the city on the Volga that bears Stalin's name. Bombing on 23 August turns it to rubble, and the battle becomes street by street, factory by factory. In November the Red Army encircles the German 6th Army, and on 2 February 1943 its last troops surrender: the turning point of the war in Europe. Here: a ruined tractor factory with broken chimneys, rubble, and the Soviet red flag.",
      position: [65.28, 4.9, -21.69],
      anchorFrom: [65.28, 0, 3.26],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [67.76, 10.9, -24.44],
      labelColor: "#e8b21f",
    },
    {
      id: 18,
      title: "23 Oct 1942 — El Alamein",
      description:
        "In Egypt, only about 100 km from Alexandria, General Montgomery's British Eighth Army attacks Rommel's German and Italian army at El Alamein. After twelve days of fighting Rommel retreats, and Egypt and the Suez Canal are safe. Churchill later wrote: 'Before Alamein we never had a victory. After Alamein we never had a defeat.' Here: a pyramid and a palm for Egypt, a British desert tank heading west, and a burning German tank.",
      position: [28.2, 4.9, 27.42],
      anchorFrom: [28.2, 0, 52.37],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [30.68, 10.9, 24.67],
      labelColor: "#e8b21f",
    },
    {
      id: 19,
      title: "8 Nov 1942 — Operation Torch",
      description:
        "American and British troops land in Morocco and Algeria, then held by Vichy France: the first big American ground campaign against Germany. Caught between Torch in the west and Montgomery in the east, the Axis armies are squeezed into Tunisia, where about 250,000 of them surrender in May 1943. North Africa is cleared, and the way to Italy is open. Here: a giant flaming torch, a landing ship and the US flag.",
      position: [-113.1, 4.94, 21.95],
      anchorFrom: [-113.1, 0, 46.89],
      anchorDistance: -24.94,
      eyeHeight: 12.71,
      labelPosition: [-110.62, 10.94, 19.2],
      labelColor: "#e8b21f",
    },
    {
      id: 20,
      title: "5 Jul 1943 — Kursk",
      description:
        "Germany's last great offensive in the East tries to cut off a Soviet bulge in the front around the city of Kursk. The Soviets knew it was coming and had dug deep defences; thousands of tanks clash, most famously at Prokhorovka, in what is often called the largest tank battle in history. Hitler calls the attack off within ten days, and from now on the Red Army keeps the initiative all the way to Berlin. Here: German and Soviet tanks clashing around an explosion.",
      position: [48.01, 4.9, -35.65],
      anchorFrom: [48.01, 0, -10.7],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [50.49, 10.9, -38.4],
      labelColor: "#ee7424",
    },
    {
      id: 21,
      title: "10 Jul 1943 — Sicily & Italy",
      description:
        "The Allies land on Sicily, beneath the smoking volcano of Mount Etna. On 25 July Mussolini is overthrown and arrested, and on 8 September Italy's new government surrenders. Germany rushes in troops, frees Mussolini and fights a slow retreat up the peninsula; Rome is not liberated until 4 June 1944. Here: Mount Etna, a toppled bronze bust of the dictator, and the US flag.",
      position: [-29.3, 4.9, 14.39],
      anchorFrom: [-29.3, 0, 39.34],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-26.83, 10.9, 11.64],
      labelColor: "#ee7424",
    },
    {
      id: 22,
      title: "6 Jun 1944 — D-Day",
      description:
        "Operation Overlord: about 156,000 American, British and Canadian troops land on five Normandy beaches (Utah, Omaha, Gold, Juno and Sword), with paratroopers dropped behind them in the night. It is the largest seaborne invasion in history. By late August the Allies have broken out of Normandy, and Paris is liberated on 25 August. Here: a landing craft with its ramp down, soldiers running up the beach between steel 'hedgehog' obstacles, and a paratrooper.",
      position: [-93.46, 4.9, -23.97],
      anchorFrom: [-93.46, 0, 0.98],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-90.99, 10.9, -26.72],
      labelColor: "#d8323c",
    },
    {
      id: 23,
      title: "22 Jun 1944 — Operation Bagration",
      description:
        "Three years to the day after Barbarossa (10), the Red Army launches a huge summer offensive in Belarus, named after Pyotr Bagration, a Russian general of 1812. It destroys most of Germany's Army Group Centre, arguably Germany's worst defeat of the war, frees Minsk and sweeps about 500 km west to the Vistula and the edge of Warsaw. Here: a red star on a pedestal, red arrows pushing west, and a Soviet T-34 tank.",
      position: [23.83, 4.94, -45.7],
      anchorFrom: [23.83, 0, -20.75],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [26.3, 10.94, -48.45],
      labelColor: "#d8323c",
    },
    {
      id: 24,
      title: "23 Oct 1944 — Leyte Gulf",
      description:
        "The Americans return to the Philippines, as General MacArthur had promised, and Japan throws almost its whole remaining navy at the landings in Leyte Gulf. In four days of battles across hundreds of kilometres of sea, the largest naval battle in history, the Japanese fleet is crippled. Japan also launches its first organised kamikaze suicide attacks. Here: two battle fleets firing at each other, a kamikaze plane diving, and white shell splashes.",
      position: [132.44, 5.0, 56.37],
      anchorFrom: [132.44, 0, 81.32],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [134.92, 11.0, 53.62],
      labelColor: "#d8323c",
    },
    {
      id: 25,
      title: "16 Dec 1944 — Battle of the Bulge",
      description:
        "In the snowy Ardennes forest, the same route his tanks took in 1940 (5), Hitler launches a surprise attack to split the Allies and retake the port of Antwerp. It pushes a 'bulge' into the American lines; surrounded at Bastogne, the US commander answers a demand to surrender with one word: 'Nuts!' By late January the bulge is gone, and Germany has spent its last reserves in the West. Here: a snowy pine forest, a big American helmet and a German tank.",
      position: [-68.49, 4.9, -27.68],
      anchorFrom: [-68.49, 0, -2.73],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-66.01, 10.9, -30.43],
      labelColor: "#d8323c",
    },
    {
      id: 26,
      title: "27 Jan 1945 — Auschwitz Liberated",
      description:
        "Soviet soldiers reach Auschwitz in occupied Poland and free about 7,000 prisoners left behind. At this complex of camps, the largest of the Nazi killing centres, about 1.1 million people were murdered, around a million of them Jews. In the Holocaust as a whole, Nazi Germany and its collaborators murdered about six million Jews, as well as millions of other victims. 27 January is now International Holocaust Remembrance Day. Here: the brick gatehouse with the railway line running through it, barbed wire, and a memorial candle.",
      position: [-7.46, 5.78, -27.82],
      anchorFrom: [-7.46, 0, -2.87],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-4.98, 11.78, -30.57],
      labelColor: "#d9429b",
    },
    {
      id: 27,
      title: "4 Feb 1945 — Yalta Conference",
      description:
        "Roosevelt, Churchill and Stalin, the 'Big Three', meet at the Livadia Palace in Yalta, in Crimea, to plan the end of the war. They agree to divide Germany into occupation zones, to hold free elections in liberated Eastern Europe (a promise Stalin would not keep), to found the United Nations, and that the Soviet Union will join the war against Japan after Germany is beaten. Here: a round table with three chairs, the white palace, and the flags of the USA, Britain and the USSR.",
      position: [43.25, 4.9, -5.61],
      anchorFrom: [43.25, 0, 19.34],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [45.73, 10.9, -8.36],
      labelColor: "#d9429b",
    },
    {
      id: 28,
      title: "19 Feb 1945 — Iwo Jima",
      description:
        "US Marines storm Iwo Jima, a small volcanic island whose airfields would bring Japan within range of fighter escorts. On 23 February they raise the flag on Mount Suribachi, captured in one of the most famous photographs of the war. Of about 21,000 Japanese defenders, dug into caves and tunnels, almost all die; nearly 7,000 Americans are killed. Here: black Mount Suribachi and the Marines raising the flag.",
      position: [156.59, 4.97, 37.48],
      anchorFrom: [156.59, 0, 62.42],
      anchorDistance: -24.94,
      eyeHeight: 12.71,
      labelPosition: [159.07, 10.97, 34.73],
      labelColor: "#d9429b",
    },
    {
      id: 29,
      title: "1 Apr 1945 — Okinawa",
      description:
        "The last and largest island assault of the Pacific war, about 550 km from Japan's home islands. For nearly three months the Japanese defenders fight to the end, while waves of kamikaze planes sink or damage hundreds of ships offshore. Over 100,000 Japanese soldiers die, and perhaps a quarter of Okinawa's civilians. Its terrible cost weighs on the decision about how to end the war. Here: the red-roofed Shuri Castle, a diving kamikaze plane and a US warship.",
      position: [137.01, 4.91, 34.79],
      anchorFrom: [137.01, 0, 59.74],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [139.49, 10.91, 32.04],
      labelColor: "#d9429b",
    },
    {
      id: 30,
      title: "16 Apr 1945 — Fall of Berlin & V-E Day",
      description:
        "The Red Army launches its final assault on Berlin. As Soviet troops fight their way into the city centre, Hitler kills himself in his bunker on 30 April; Berlin surrenders on 2 May, and the Soviet red flag flies over the Reichstag. Germany surrenders unconditionally, and 8 May is celebrated as V-E Day, Victory in Europe (9 May in Russia). Here: the Reichstag with the red flag on its roof, rubble, and Allied soldiers.",
      position: [-33.47, 4.9, -39.46],
      anchorFrom: [-33.47, 0, -14.51],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [-31.0, 10.9, -42.21],
      labelColor: "#d9429b",
    },
    {
      id: 31,
      title: "6 Aug 1945 — Hiroshima & Nagasaki",
      description:
        "The United States drops an atomic bomb on Hiroshima, destroying most of the city in an instant; a second bomb falls on Nagasaki on 9 August. Together they kill well over 100,000 people by the end of the year. On 8 August the Soviet Union declares war on Japan and invades Manchuria, and on 15 August Emperor Hirohito announces Japan's surrender by radio. Here: a mushroom cloud rising beside the skeleton dome that still stands in Hiroshima as the Peace Memorial.",
      position: [144.56, 6.36, 20.47],
      anchorFrom: [144.56, 0, 45.42],
      anchorDistance: -24.95,
      eyeHeight: 12.72,
      labelPosition: [147.03, 12.36, 17.73],
      labelColor: "#d9429b",
    },
    {
      id: 32,
      title: "2 Sep 1945 — Japan Surrenders",
      description:
        "On the deck of the battleship USS Missouri in Tokyo Bay, Japan's foreign minister and its army chief of staff sign the instrument of surrender, and General MacArthur signs for the Allies. Six years and one day after Germany invaded Poland (2), the Second World War is over. It had killed an estimated 70 to 85 million people. Here: the USS Missouri with the signing table on deck, and a white dove of peace.",
      position: [154.77, 4.9, 18.66],
      anchorFrom: [154.77, 0, 43.61],
      anchorDistance: -24.95,
      eyeHeight: 12.71,
      labelPosition: [157.24, 10.9, 15.91],
      labelColor: "#d9429b",
    },
  ],
};
