"""Export-time preparation for the `india-history` scene ("River of Time").

Source: blender_models/IndiaHistory.blend, itself generated by the scripts in
blender_models/india_history_scenegen/ (ih_*.py). A serpentine road runs beside
a river past 25 plateaus, one per event, each with a numbered sign and a
low-poly monument; six era gates arch over the road. Locus_01..25 are baked into
the .blend as children of Station_NN empties, sitting on each monument's aim
point (mid-height for the tall ones), so build_glb.py's SCENES entry is empty.

What this module does, in memory only (the .blend is never saved):
  * drops the Blender-only rig -- cameras (incl. the animated Cam_Tour), the
    sun, Tour_Target -- and the cloud layer, which floats ~180 m up and would
    throw moving-looking blotches of shadow over everything once Viewer sets
    castShadow on every mesh;
  * flattens the ~200 text objects (sign boards, gate lintels) to zero extrude
    and resolution_u 2 before bake_curves_to_meshes() turns them into meshes:
    extruded, full-resolution glyphs would triple the scene's triangle count
    for letter sides nobody sees;
  * recentres the whole scene on the origin. Viewer's shadow camera is a box
    centred on the origin, and this scene's footprint (about 370 x 285 m) is
    otherwise off to one side of it -- OFFSET is subtracted from every root
    object, so shadowExtent ~190 in the scene config covers all of it.

prune_empties() runs after merge_by_material(): once the meshes are merged
away, the hundreds of little sub-frame empties the generator used for local
positioning are childless and just bloat the glb's node list. Station_NN and
Locus_NN are kept.
"""
import bpy

# Blender-space point subtracted from every root object (x, y). The scene
# config's camera numbers already have this applied.
OFFSET = (95.0, 72.0)

DROP_NAMES = ("Tour_Target", "Clouds")


def prepare():
    dropped = 0
    for ob in list(bpy.data.objects):
        if ob.type in ("CAMERA", "LIGHT") or ob.name in DROP_NAMES:
            bpy.data.objects.remove(ob, do_unlink=True)
            dropped += 1
    texts = 0
    for cu in bpy.data.curves:
        if isinstance(cu, bpy.types.TextCurve):
            cu.extrude = 0.0
            cu.bevel_depth = 0.0
            cu.resolution_u = 2
            texts += 1
    for ob in bpy.data.objects:
        if ob.parent is None:
            ob.location.x -= OFFSET[0]
            ob.location.y -= OFFSET[1]
    bpy.context.view_layer.update()
    print("india-history: dropped %d rig objects, flattened %d texts, recentred by %s"
          % (dropped, texts, OFFSET))


def prune_empties():
    keep = ("Station_", "Locus_")
    removed = 0
    changed = True
    while changed:
        changed = False
        for ob in list(bpy.data.objects):
            if ob.type == "EMPTY" and not ob.children and not ob.name.startswith(keep):
                bpy.data.objects.remove(ob, do_unlink=True)
                removed += 1
                changed = True
    print("india-history: pruned %d childless helper empties" % removed)
