"""Export-time preparation for the `world-war-2` scene ("Theatre of War").

Source: blender_models/WorldWarII.blend, generated by the scripts in
blender_models/ww2_scenegen/ (ww2_*.py). A low-poly world map sits on a wooden
war-room table; 32 events stand where they happened, each on a hex plinth with a
low-poly monument, a brass pole and a tilted sign, and glowing bezier arcs join
them in date order. Locus_01..32 are baked into the .blend (one per event, on
the monument's aim point), so build_glb.py's SCENES entry is empty.

What this module does, in memory only (the .blend is never saved):
  * drops the Blender-only rig -- cameras and suns -- plus the number medallion
    discs (Medallion_NN) and their digits (Num_NN). In the viewer the numbered
    badge is a LocusLabels sprite parked exactly where the medallion was
    (labelPosition in the scene config) and tinted with the event's year colour
    (labelColor), so it stays readable from every angle and stays clickable.
    The brass poles are kept: the badge sits on top of its pole like a map pin;
  * flattens the ~200 text objects (signs, timeline, title) to zero extrude and
    low curve resolution before bake_curves_to_meshes() turns them into meshes;
  * scales the whole scene up by SCALE. The .blend is authored with the map
    ~82 units wide and monuments ~1.3 units tall; x5 puts it at roughly the
    metre scale of india-history (monuments ~6.5 m, map ~410 m), so the
    viewer's fixed 0.1 near plane, shadow bias and FreeMove speed all behave.
    The map is already centred on the origin, so no recentring is needed.
"""
import bpy

SCALE = 5.0

DROP_PREFIXES = ("Medallion_", "Num_", "Cam_")


def prepare():
    dropped = 0
    for ob in list(bpy.data.objects):
        if ob.type in ("CAMERA", "LIGHT") or ob.name.startswith(DROP_PREFIXES):
            bpy.data.objects.remove(ob, do_unlink=True)
            dropped += 1
    texts = 0
    for cu in bpy.data.curves:
        if isinstance(cu, bpy.types.TextCurve):
            cu.extrude = 0.0
            cu.bevel_depth = 0.0
            cu.resolution_u = 3
            texts += 1
        else:
            # the date-order path arcs: 24 segments x 6-sided tube is plenty
            cu.resolution_u = 16
            cu.bevel_resolution = 1
    for ob in bpy.data.objects:
        if ob.parent is None:
            ob.location = ob.location * SCALE
            ob.scale = ob.scale * SCALE
    bpy.context.view_layer.update()
    print("world-war-2: dropped %d rig/medallion objects, flattened %d texts, scaled x%g"
          % (dropped, texts, SCALE))
